/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthCheckoutPost200Response,
  AuthInvoicesGet200Response,
  AuthInvoicesInvoiceIdGet200Response,
  AuthOnboardingStepPutRequest,
  GetBillingPortal200Response,
  GetCredits200Response,
  GetMe200Response,
  GetRecentActivity200Response,
  GithubCallback200Response,
  GithubCallback400Response,
  Logout200Response,
} from '../models/index';
import {
    AuthCheckoutPost200ResponseFromJSON,
    AuthCheckoutPost200ResponseToJSON,
    AuthInvoicesGet200ResponseFromJSON,
    AuthInvoicesGet200ResponseToJSON,
    AuthInvoicesInvoiceIdGet200ResponseFromJSON,
    AuthInvoicesInvoiceIdGet200ResponseToJSON,
    AuthOnboardingStepPutRequestFromJSON,
    AuthOnboardingStepPutRequestToJSON,
    GetBillingPortal200ResponseFromJSON,
    GetBillingPortal200ResponseToJSON,
    GetCredits200ResponseFromJSON,
    GetCredits200ResponseToJSON,
    GetMe200ResponseFromJSON,
    GetMe200ResponseToJSON,
    GetRecentActivity200ResponseFromJSON,
    GetRecentActivity200ResponseToJSON,
    GithubCallback200ResponseFromJSON,
    GithubCallback200ResponseToJSON,
    GithubCallback400ResponseFromJSON,
    GithubCallback400ResponseToJSON,
    Logout200ResponseFromJSON,
    Logout200ResponseToJSON,
} from '../models/index';

export interface AuthInvoicesGetRequest {
    page?: number;
    limit?: number;
}

export interface AuthInvoicesInvoiceIdGetRequest {
    invoiceId: string;
}

export interface AuthOnboardingStepPutOperationRequest {
    authOnboardingStepPutRequest: AuthOnboardingStepPutRequest;
}

export interface GetBillingPortalRequest {
    userId: string;
}

export interface GithubCallbackRequest {
    code?: string;
    state?: string;
    error?: string;
    errorDescription?: string;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Create a Polar checkout session URL for subscription
     */
    async authCheckoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthCheckoutPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/checkout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthCheckoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a Polar checkout session URL for subscription
     */
    async authCheckoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthCheckoutPost200Response> {
        const response = await this.authCheckoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * List previous invoices from Polar
     */
    async authInvoicesGetRaw(requestParameters: AuthInvoicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthInvoicesGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/invoices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthInvoicesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List previous invoices from Polar
     */
    async authInvoicesGet(requestParameters: AuthInvoicesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthInvoicesGet200Response> {
        const response = await this.authInvoicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific invoice URL from Polar
     */
    async authInvoicesInvoiceIdGetRaw(requestParameters: AuthInvoicesInvoiceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthInvoicesInvoiceIdGet200Response>> {
        if (requestParameters['invoiceId'] == null) {
            throw new runtime.RequiredError(
                'invoiceId',
                'Required parameter "invoiceId" was null or undefined when calling authInvoicesInvoiceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/invoices/{invoiceId}`;
        urlPath = urlPath.replace(`{${"invoiceId"}}`, encodeURIComponent(String(requestParameters['invoiceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthInvoicesInvoiceIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific invoice URL from Polar
     */
    async authInvoicesInvoiceIdGet(requestParameters: AuthInvoicesInvoiceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthInvoicesInvoiceIdGet200Response> {
        const response = await this.authInvoicesInvoiceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the onboarding step for the authenticated user
     */
    async authOnboardingStepPutRaw(requestParameters: AuthOnboardingStepPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        if (requestParameters['authOnboardingStepPutRequest'] == null) {
            throw new runtime.RequiredError(
                'authOnboardingStepPutRequest',
                'Required parameter "authOnboardingStepPutRequest" was null or undefined when calling authOnboardingStepPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/onboarding-step`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AuthOnboardingStepPutRequestToJSON(requestParameters['authOnboardingStepPutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Update the onboarding step for the authenticated user
     */
    async authOnboardingStepPut(requestParameters: AuthOnboardingStepPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.authOnboardingStepPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get customer portal URL for managing payment details in Polar
     */
    async getBillingPortalRaw(requestParameters: GetBillingPortalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBillingPortal200Response>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getBillingPortal().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/billing`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBillingPortal200ResponseFromJSON(jsonValue));
    }

    /**
     * Get customer portal URL for managing payment details in Polar
     */
    async getBillingPortal(requestParameters: GetBillingPortalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBillingPortal200Response> {
        const response = await this.getBillingPortalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user credit usage and subscription status
     */
    async getCreditsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCredits200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/credits`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCredits200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user credit usage and subscription status
     */
    async getCredits(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCredits200Response> {
        const response = await this.getCreditsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current authenticated user information with billing status
     */
    async getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetMe200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetMe200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current authenticated user information with billing status
     */
    async getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetMe200Response> {
        const response = await this.getMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get user statistics and recent activity
     */
    async getRecentActivityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRecentActivity200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/me/recent-activity`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRecentActivity200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user statistics and recent activity
     */
    async getRecentActivity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRecentActivity200Response> {
        const response = await this.getRecentActivityRaw(initOverrides);
        return await response.value();
    }

    /**
     * GitHub OAuth callback endpoint
     */
    async githubCallbackRaw(requestParameters: GithubCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubCallback200Response>> {
        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        if (requestParameters['errorDescription'] != null) {
            queryParameters['error_description'] = requestParameters['errorDescription'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubCallback200ResponseFromJSON(jsonValue));
    }

    /**
     * GitHub OAuth callback endpoint
     */
    async githubCallback(requestParameters: GithubCallbackRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubCallback200Response> {
        const response = await this.githubCallbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout and clear authentication cookie
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Logout and clear authentication cookie
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

}
