/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTemplate400Response,
  GenerateDocument200Response,
  GenerateDocumentRequest,
  GetGenerationStats200Response,
  GetUsageStats200Response,
  ListGenerationRecords200Response,
} from '../models/index';
import {
    CreateTemplate400ResponseFromJSON,
    CreateTemplate400ResponseToJSON,
    GenerateDocument200ResponseFromJSON,
    GenerateDocument200ResponseToJSON,
    GenerateDocumentRequestFromJSON,
    GenerateDocumentRequestToJSON,
    GetGenerationStats200ResponseFromJSON,
    GetGenerationStats200ResponseToJSON,
    GetUsageStats200ResponseFromJSON,
    GetUsageStats200ResponseToJSON,
    ListGenerationRecords200ResponseFromJSON,
    ListGenerationRecords200ResponseToJSON,
} from '../models/index';

export interface GenerateDocumentOperationRequest {
    generateDocumentRequest?: GenerateDocumentRequest;
}

export interface ListGenerationRecordsRequest {
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class DocumentsApi extends runtime.BaseAPI {

    /**
     * Generate a PDF document from a template
     */
    async generateDocumentRaw(requestParameters: GenerateDocumentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateDocument200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/generate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateDocumentRequestToJSON(requestParameters['generateDocumentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateDocument200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate a PDF document from a template
     */
    async generateDocument(requestParameters: GenerateDocumentOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateDocument200Response> {
        const response = await this.generateDocumentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get overall generation statistics (total PDFs, success rate, failures)
     */
    async getGenerationStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGenerationStats200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/documents/generation-stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGenerationStats200ResponseFromJSON(jsonValue));
    }

    /**
     * Get overall generation statistics (total PDFs, success rate, failures)
     */
    async getGenerationStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGenerationStats200Response> {
        const response = await this.getGenerationStatsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get document generation usage statistics for the last 7 days
     */
    async getUsageStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUsageStats200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/documents/usage-stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUsageStats200ResponseFromJSON(jsonValue));
    }

    /**
     * Get document generation usage statistics for the last 7 days
     */
    async getUsageStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUsageStats200Response> {
        const response = await this.getUsageStatsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List generation records for the authenticated user
     */
    async listGenerationRecordsRaw(requestParameters: ListGenerationRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListGenerationRecords200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/documents/records`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListGenerationRecords200ResponseFromJSON(jsonValue));
    }

    /**
     * List generation records for the authenticated user
     */
    async listGenerationRecords(requestParameters: ListGenerationRecordsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListGenerationRecords200Response> {
        const response = await this.listGenerationRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
