/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  McpResourcesReadPostRequest,
  McpServerInfoGet200Response,
  McpToolsCallPostRequest,
  McpWellKnownMcpJsonGet200Response,
} from '../models/index';
import {
    McpResourcesReadPostRequestFromJSON,
    McpResourcesReadPostRequestToJSON,
    McpServerInfoGet200ResponseFromJSON,
    McpServerInfoGet200ResponseToJSON,
    McpToolsCallPostRequestFromJSON,
    McpToolsCallPostRequestToJSON,
    McpWellKnownMcpJsonGet200ResponseFromJSON,
    McpWellKnownMcpJsonGet200ResponseToJSON,
} from '../models/index';

export interface McpResourcesReadPostOperationRequest {
    mcpResourcesReadPostRequest: McpResourcesReadPostRequest;
}

export interface McpToolsCallPostOperationRequest {
    mcpToolsCallPostRequest: McpToolsCallPostRequest;
}

/**
 * 
 */
export class MCPApi extends runtime.BaseAPI {

    /**
     * Returns all templates as MCP resources that can be read. Response is in Server-Sent Events format.
     * List available MCP resources
     */
    async mcpResourcesListPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }


        let urlPath = `/mcp/resources/list`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns all templates as MCP resources that can be read. Response is in Server-Sent Events format.
     * List available MCP resources
     */
    async mcpResourcesListPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.mcpResourcesListPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the HTML content of a specific template by its URI (template://templateId). Response is in Server-Sent Events format.
     * Read an MCP resource
     */
    async mcpResourcesReadPostRaw(requestParameters: McpResourcesReadPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['mcpResourcesReadPostRequest'] == null) {
            throw new runtime.RequiredError(
                'mcpResourcesReadPostRequest',
                'Required parameter "mcpResourcesReadPostRequest" was null or undefined when calling mcpResourcesReadPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }


        let urlPath = `/mcp/resources/read`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: McpResourcesReadPostRequestToJSON(requestParameters['mcpResourcesReadPostRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get the HTML content of a specific template by its URI (template://templateId). Response is in Server-Sent Events format.
     * Read an MCP resource
     */
    async mcpResourcesReadPost(requestParameters: McpResourcesReadPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.mcpResourcesReadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns MCP protocol version and server capabilities
     * Get MCP server information
     */
    async mcpServerInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<McpServerInfoGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mcp/server-info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => McpServerInfoGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns MCP protocol version and server capabilities
     * Get MCP server information
     */
    async mcpServerInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<McpServerInfoGet200Response> {
        const response = await this.mcpServerInfoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Execute a tool like generate_pdf, list_templates, get_template_details, or get_user_credits. Response is in Server-Sent Events format.
     * Call an MCP tool
     */
    async mcpToolsCallPostRaw(requestParameters: McpToolsCallPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['mcpToolsCallPostRequest'] == null) {
            throw new runtime.RequiredError(
                'mcpToolsCallPostRequest',
                'Required parameter "mcpToolsCallPostRequest" was null or undefined when calling mcpToolsCallPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }


        let urlPath = `/mcp/tools/call`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: McpToolsCallPostRequestToJSON(requestParameters['mcpToolsCallPostRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Execute a tool like generate_pdf, list_templates, get_template_details, or get_user_credits. Response is in Server-Sent Events format.
     * Call an MCP tool
     */
    async mcpToolsCallPost(requestParameters: McpToolsCallPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.mcpToolsCallPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all tools available for AI assistants to use (generate_pdf, list_templates, etc.). Response is in Server-Sent Events format.
     * List available MCP tools
     */
    async mcpToolsListPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }


        let urlPath = `/mcp/tools/list`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns all tools available for AI assistants to use (generate_pdf, list_templates, etc.). Response is in Server-Sent Events format.
     * List available MCP tools
     */
    async mcpToolsListPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.mcpToolsListPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns MCP server configuration for ChatGPT and other AI assistants
     * MCP discovery endpoint
     */
    async mcpWellKnownMcpJsonGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<McpWellKnownMcpJsonGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mcp/.well-known/mcp.json`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => McpWellKnownMcpJsonGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns MCP server configuration for ChatGPT and other AI assistants
     * MCP discovery endpoint
     */
    async mcpWellKnownMcpJsonGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<McpWellKnownMcpJsonGet200Response> {
        const response = await this.mcpWellKnownMcpJsonGetRaw(initOverrides);
        return await response.value();
    }

}
