/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateStorageConfig400Response,
  CreateStorageConfigRequest,
  GetStorageConfig200Response,
  ListStorageConfigs200Response,
  Logout200Response,
  UpdateStorageConfigRequest,
} from '../models/index';
import {
    CreateStorageConfig400ResponseFromJSON,
    CreateStorageConfig400ResponseToJSON,
    CreateStorageConfigRequestFromJSON,
    CreateStorageConfigRequestToJSON,
    GetStorageConfig200ResponseFromJSON,
    GetStorageConfig200ResponseToJSON,
    ListStorageConfigs200ResponseFromJSON,
    ListStorageConfigs200ResponseToJSON,
    Logout200ResponseFromJSON,
    Logout200ResponseToJSON,
    UpdateStorageConfigRequestFromJSON,
    UpdateStorageConfigRequestToJSON,
} from '../models/index';

export interface CreateStorageConfigOperationRequest {
    createStorageConfigRequest: CreateStorageConfigRequest;
}

export interface DeleteStorageConfigRequest {
    storageKey: string;
}

export interface GetStorageConfigRequest {
    storageKey: string;
}

export interface UpdateStorageConfigOperationRequest {
    storageKey: string;
    updateStorageConfigRequest: UpdateStorageConfigRequest;
}

/**
 * 
 */
export class StorageApi extends runtime.BaseAPI {

    /**
     * Create a new storage configuration
     */
    async createStorageConfigRaw(requestParameters: CreateStorageConfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        if (requestParameters['createStorageConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'createStorageConfigRequest',
                'Required parameter "createStorageConfigRequest" was null or undefined when calling createStorageConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStorageConfigRequestToJSON(requestParameters['createStorageConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new storage configuration
     */
    async createStorageConfig(requestParameters: CreateStorageConfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.createStorageConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a storage configuration
     */
    async deleteStorageConfigRaw(requestParameters: DeleteStorageConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        if (requestParameters['storageKey'] == null) {
            throw new runtime.RequiredError(
                'storageKey',
                'Required parameter "storageKey" was null or undefined when calling deleteStorageConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config/{storageKey}`;
        urlPath = urlPath.replace(`{${"storageKey"}}`, encodeURIComponent(String(requestParameters['storageKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a storage configuration
     */
    async deleteStorageConfig(requestParameters: DeleteStorageConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.deleteStorageConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a storage configuration by key
     */
    async getStorageConfigRaw(requestParameters: GetStorageConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStorageConfig200Response>> {
        if (requestParameters['storageKey'] == null) {
            throw new runtime.RequiredError(
                'storageKey',
                'Required parameter "storageKey" was null or undefined when calling getStorageConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config/{storageKey}`;
        urlPath = urlPath.replace(`{${"storageKey"}}`, encodeURIComponent(String(requestParameters['storageKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStorageConfig200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a storage configuration by key
     */
    async getStorageConfig(requestParameters: GetStorageConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStorageConfig200Response> {
        const response = await this.getStorageConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all storage configurations
     */
    async listStorageConfigsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListStorageConfigs200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-configs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListStorageConfigs200ResponseFromJSON(jsonValue));
    }

    /**
     * List all storage configurations
     */
    async listStorageConfigs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListStorageConfigs200Response> {
        const response = await this.listStorageConfigsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a storage configuration
     */
    async updateStorageConfigRaw(requestParameters: UpdateStorageConfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        if (requestParameters['storageKey'] == null) {
            throw new runtime.RequiredError(
                'storageKey',
                'Required parameter "storageKey" was null or undefined when calling updateStorageConfig().'
            );
        }

        if (requestParameters['updateStorageConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'updateStorageConfigRequest',
                'Required parameter "updateStorageConfigRequest" was null or undefined when calling updateStorageConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config/{storageKey}`;
        urlPath = urlPath.replace(`{${"storageKey"}}`, encodeURIComponent(String(requestParameters['storageKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateStorageConfigRequestToJSON(requestParameters['updateStorageConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Update a storage configuration
     */
    async updateStorageConfig(requestParameters: UpdateStorageConfigOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.updateStorageConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
