/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTemplate200Response,
  CreateTemplate400Response,
  CreateTemplateRequest,
  GenerateTemplateFromPdf500Response,
  GenerateTemplateFromPromptRequest,
  ListTemplates200Response,
  ListTemplates200ResponseTemplatesInner,
  Logout200Response,
  UpdateTemplateRequest,
} from '../models/index';
import {
    CreateTemplate200ResponseFromJSON,
    CreateTemplate200ResponseToJSON,
    CreateTemplate400ResponseFromJSON,
    CreateTemplate400ResponseToJSON,
    CreateTemplateRequestFromJSON,
    CreateTemplateRequestToJSON,
    GenerateTemplateFromPdf500ResponseFromJSON,
    GenerateTemplateFromPdf500ResponseToJSON,
    GenerateTemplateFromPromptRequestFromJSON,
    GenerateTemplateFromPromptRequestToJSON,
    ListTemplates200ResponseFromJSON,
    ListTemplates200ResponseToJSON,
    ListTemplates200ResponseTemplatesInnerFromJSON,
    ListTemplates200ResponseTemplatesInnerToJSON,
    Logout200ResponseFromJSON,
    Logout200ResponseToJSON,
    UpdateTemplateRequestFromJSON,
    UpdateTemplateRequestToJSON,
} from '../models/index';

export interface CreateTemplateOperationRequest {
    createTemplateRequest: CreateTemplateRequest;
}

export interface DeleteTemplateRequest {
    templateId: string;
}

export interface GenerateTemplateFromPdfRequest {
    file: Blob;
}

export interface GenerateTemplateFromPromptOperationRequest {
    generateTemplateFromPromptRequest: GenerateTemplateFromPromptRequest;
}

export interface GetTemplateRequest {
    templateId: string;
}

export interface UpdateTemplateOperationRequest {
    templateId: string;
    updateTemplateRequest?: UpdateTemplateRequest;
}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI {

    /**
     * Create a new HTML template
     */
    async createTemplateRaw(requestParameters: CreateTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTemplate200Response>> {
        if (requestParameters['createTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'createTemplateRequest',
                'Required parameter "createTemplateRequest" was null or undefined when calling createTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTemplateRequestToJSON(requestParameters['createTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTemplate200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new HTML template
     */
    async createTemplate(requestParameters: CreateTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTemplate200Response> {
        const response = await this.createTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a template
     */
    async deleteTemplateRaw(requestParameters: DeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Logout200Response>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling deleteTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/{templateId}`;
        urlPath = urlPath.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Logout200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a template
     */
    async deleteTemplate(requestParameters: DeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Logout200Response> {
        const response = await this.deleteTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate HTML template from PDF file using AI. Upload a PDF file using multipart/form-data with field name \"file\". The generated template will be automatically saved to the database.
     */
    async generateTemplateFromPdfRaw(requestParameters: GenerateTemplateFromPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTemplate200Response>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling generateTemplateFromPdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/templates/generate-from-pdf`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTemplate200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate HTML template from PDF file using AI. Upload a PDF file using multipart/form-data with field name \"file\". The generated template will be automatically saved to the database.
     */
    async generateTemplateFromPdf(requestParameters: GenerateTemplateFromPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTemplate200Response> {
        const response = await this.generateTemplateFromPdfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate HTML template from AI prompt. Provide a description of the template you want and the data fields to inject.
     */
    async generateTemplateFromPromptRaw(requestParameters: GenerateTemplateFromPromptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTemplate200Response>> {
        if (requestParameters['generateTemplateFromPromptRequest'] == null) {
            throw new runtime.RequiredError(
                'generateTemplateFromPromptRequest',
                'Required parameter "generateTemplateFromPromptRequest" was null or undefined when calling generateTemplateFromPrompt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/generate-from-prompt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateTemplateFromPromptRequestToJSON(requestParameters['generateTemplateFromPromptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTemplate200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate HTML template from AI prompt. Provide a description of the template you want and the data fields to inject.
     */
    async generateTemplateFromPrompt(requestParameters: GenerateTemplateFromPromptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTemplate200Response> {
        const response = await this.generateTemplateFromPromptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a template by ID
     */
    async getTemplateRaw(requestParameters: GetTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTemplates200ResponseTemplatesInner>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/{templateId}`;
        urlPath = urlPath.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTemplates200ResponseTemplatesInnerFromJSON(jsonValue));
    }

    /**
     * Get a template by ID
     */
    async getTemplate(requestParameters: GetTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTemplates200ResponseTemplatesInner> {
        const response = await this.getTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all templates for authenticated user
     */
    async listTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTemplates200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTemplates200ResponseFromJSON(jsonValue));
    }

    /**
     * List all templates for authenticated user
     */
    async listTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTemplates200Response> {
        const response = await this.listTemplatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a template
     */
    async updateTemplateRaw(requestParameters: UpdateTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTemplate200Response>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling updateTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/{templateId}`;
        urlPath = urlPath.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTemplateRequestToJSON(requestParameters['updateTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTemplate200ResponseFromJSON(jsonValue));
    }

    /**
     * Update a template
     */
    async updateTemplate(requestParameters: UpdateTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTemplate200Response> {
        const response = await this.updateTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
