/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebhooksPolarPostRequest,
} from '../models/index';
import {
    WebhooksPolarPostRequestFromJSON,
    WebhooksPolarPostRequestToJSON,
} from '../models/index';

export interface WebhooksPolarPostOperationRequest {
    webhooksPolarPostRequest?: WebhooksPolarPostRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Handle Polar webhook events
     */
    async webhooksPolarPostRaw(requestParameters: WebhooksPolarPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/webhooks/polar`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhooksPolarPostRequestToJSON(requestParameters['webhooksPolarPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handle Polar webhook events
     */
    async webhooksPolarPost(requestParameters: WebhooksPolarPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.webhooksPolarPostRaw(requestParameters, initOverrides);
    }

}
