/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthOnboardingStepPutRequest
 */
export interface AuthOnboardingStepPutRequest {
    /**
     * Onboarding step number
     * @type {number}
     * @memberof AuthOnboardingStepPutRequest
     */
    step: number;
}

/**
 * Check if a given object implements the AuthOnboardingStepPutRequest interface.
 */
export function instanceOfAuthOnboardingStepPutRequest(value: object): value is AuthOnboardingStepPutRequest {
    if (!('step' in value) || value['step'] === undefined) return false;
    return true;
}

export function AuthOnboardingStepPutRequestFromJSON(json: any): AuthOnboardingStepPutRequest {
    return AuthOnboardingStepPutRequestFromJSONTyped(json, false);
}

export function AuthOnboardingStepPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthOnboardingStepPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'],
    };
}

export function AuthOnboardingStepPutRequestToJSON(json: any): AuthOnboardingStepPutRequest {
    return AuthOnboardingStepPutRequestToJSONTyped(json, false);
}

export function AuthOnboardingStepPutRequestToJSONTyped(value?: AuthOnboardingStepPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': value['step'],
    };
}

