/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCheckoutPost200Response
 */
export interface AuthCheckoutPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthCheckoutPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthCheckoutPost200Response
     */
    checkoutUrl?: string;
}

/**
 * Check if a given object implements the AuthCheckoutPost200Response interface.
 */
export function instanceOfAuthCheckoutPost200Response(value: object): value is AuthCheckoutPost200Response {
    return true;
}

export function AuthCheckoutPost200ResponseFromJSON(json: any): AuthCheckoutPost200Response {
    return AuthCheckoutPost200ResponseFromJSONTyped(json, false);
}

export function AuthCheckoutPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCheckoutPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'checkoutUrl': json['checkoutUrl'] == null ? undefined : json['checkoutUrl'],
    };
}

export function AuthCheckoutPost200ResponseToJSON(json: any): AuthCheckoutPost200Response {
    return AuthCheckoutPost200ResponseToJSONTyped(json, false);
}

export function AuthCheckoutPost200ResponseToJSONTyped(value?: AuthCheckoutPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'checkoutUrl': value['checkoutUrl'],
    };
}

