/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthInvoicesGet200ResponsePagination
 */
export interface AuthInvoicesGet200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof AuthInvoicesGet200ResponsePagination
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AuthInvoicesGet200ResponsePagination
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof AuthInvoicesGet200ResponsePagination
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AuthInvoicesGet200ResponsePagination
     */
    maxPage?: number;
}

/**
 * Check if a given object implements the AuthInvoicesGet200ResponsePagination interface.
 */
export function instanceOfAuthInvoicesGet200ResponsePagination(value: object): value is AuthInvoicesGet200ResponsePagination {
    return true;
}

export function AuthInvoicesGet200ResponsePaginationFromJSON(json: any): AuthInvoicesGet200ResponsePagination {
    return AuthInvoicesGet200ResponsePaginationFromJSONTyped(json, false);
}

export function AuthInvoicesGet200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthInvoicesGet200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'maxPage': json['maxPage'] == null ? undefined : json['maxPage'],
    };
}

export function AuthInvoicesGet200ResponsePaginationToJSON(json: any): AuthInvoicesGet200ResponsePagination {
    return AuthInvoicesGet200ResponsePaginationToJSONTyped(json, false);
}

export function AuthInvoicesGet200ResponsePaginationToJSONTyped(value?: AuthInvoicesGet200ResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'totalCount': value['totalCount'],
        'maxPage': value['maxPage'],
    };
}

