/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthInvoicesInvoiceIdGet200Response
 */
export interface AuthInvoicesInvoiceIdGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthInvoicesInvoiceIdGet200Response
     */
    success?: boolean;
    /**
     * URL to download the invoice PDF
     * @type {string}
     * @memberof AuthInvoicesInvoiceIdGet200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the AuthInvoicesInvoiceIdGet200Response interface.
 */
export function instanceOfAuthInvoicesInvoiceIdGet200Response(value: object): value is AuthInvoicesInvoiceIdGet200Response {
    return true;
}

export function AuthInvoicesInvoiceIdGet200ResponseFromJSON(json: any): AuthInvoicesInvoiceIdGet200Response {
    return AuthInvoicesInvoiceIdGet200ResponseFromJSONTyped(json, false);
}

export function AuthInvoicesInvoiceIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthInvoicesInvoiceIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function AuthInvoicesInvoiceIdGet200ResponseToJSON(json: any): AuthInvoicesInvoiceIdGet200Response {
    return AuthInvoicesInvoiceIdGet200ResponseToJSONTyped(json, false);
}

export function AuthInvoicesInvoiceIdGet200ResponseToJSONTyped(value?: AuthInvoicesInvoiceIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'url': value['url'],
    };
}

