/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthInvoicesGet200ResponsePagination } from './AuthInvoicesGet200ResponsePagination';
import {
    AuthInvoicesGet200ResponsePaginationFromJSON,
    AuthInvoicesGet200ResponsePaginationFromJSONTyped,
    AuthInvoicesGet200ResponsePaginationToJSON,
    AuthInvoicesGet200ResponsePaginationToJSONTyped,
} from './AuthInvoicesGet200ResponsePagination';
import type { AuthInvoicesGet200ResponseInvoicesInner } from './AuthInvoicesGet200ResponseInvoicesInner';
import {
    AuthInvoicesGet200ResponseInvoicesInnerFromJSON,
    AuthInvoicesGet200ResponseInvoicesInnerFromJSONTyped,
    AuthInvoicesGet200ResponseInvoicesInnerToJSON,
    AuthInvoicesGet200ResponseInvoicesInnerToJSONTyped,
} from './AuthInvoicesGet200ResponseInvoicesInner';

/**
 * 
 * @export
 * @interface AuthInvoicesGet200Response
 */
export interface AuthInvoicesGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthInvoicesGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<AuthInvoicesGet200ResponseInvoicesInner>}
     * @memberof AuthInvoicesGet200Response
     */
    invoices?: Array<AuthInvoicesGet200ResponseInvoicesInner>;
    /**
     * 
     * @type {AuthInvoicesGet200ResponsePagination}
     * @memberof AuthInvoicesGet200Response
     */
    pagination?: AuthInvoicesGet200ResponsePagination;
}

/**
 * Check if a given object implements the AuthInvoicesGet200Response interface.
 */
export function instanceOfAuthInvoicesGet200Response(value: object): value is AuthInvoicesGet200Response {
    return true;
}

export function AuthInvoicesGet200ResponseFromJSON(json: any): AuthInvoicesGet200Response {
    return AuthInvoicesGet200ResponseFromJSONTyped(json, false);
}

export function AuthInvoicesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthInvoicesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'invoices': json['invoices'] == null ? undefined : ((json['invoices'] as Array<any>).map(AuthInvoicesGet200ResponseInvoicesInnerFromJSON)),
        'pagination': json['pagination'] == null ? undefined : AuthInvoicesGet200ResponsePaginationFromJSON(json['pagination']),
    };
}

export function AuthInvoicesGet200ResponseToJSON(json: any): AuthInvoicesGet200Response {
    return AuthInvoicesGet200ResponseToJSONTyped(json, false);
}

export function AuthInvoicesGet200ResponseToJSONTyped(value?: AuthInvoicesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'invoices': value['invoices'] == null ? undefined : ((value['invoices'] as Array<any>).map(AuthInvoicesGet200ResponseInvoicesInnerToJSON)),
        'pagination': AuthInvoicesGet200ResponsePaginationToJSON(value['pagination']),
    };
}

