/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthInvoicesGet200ResponseInvoicesInner
 */
export interface AuthInvoicesGet200ResponseInvoicesInner {
    /**
     * 
     * @type {string}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    status?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    paid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    invoiceNumber?: string;
    /**
     * Amount in cents
     * @type {number}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    currency?: string;
    /**
     * Amount due in cents
     * @type {number}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    dueAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    billingReason?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthInvoicesGet200ResponseInvoicesInner
     */
    isInvoiceGenerated?: boolean;
}

/**
 * Check if a given object implements the AuthInvoicesGet200ResponseInvoicesInner interface.
 */
export function instanceOfAuthInvoicesGet200ResponseInvoicesInner(value: object): value is AuthInvoicesGet200ResponseInvoicesInner {
    return true;
}

export function AuthInvoicesGet200ResponseInvoicesInnerFromJSON(json: any): AuthInvoicesGet200ResponseInvoicesInner {
    return AuthInvoicesGet200ResponseInvoicesInnerFromJSONTyped(json, false);
}

export function AuthInvoicesGet200ResponseInvoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthInvoicesGet200ResponseInvoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'status': json['status'] == null ? undefined : json['status'],
        'paid': json['paid'] == null ? undefined : json['paid'],
        'invoiceNumber': json['invoiceNumber'] == null ? undefined : json['invoiceNumber'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'dueAmount': json['dueAmount'] == null ? undefined : json['dueAmount'],
        'billingReason': json['billingReason'] == null ? undefined : json['billingReason'],
        'isInvoiceGenerated': json['isInvoiceGenerated'] == null ? undefined : json['isInvoiceGenerated'],
    };
}

export function AuthInvoicesGet200ResponseInvoicesInnerToJSON(json: any): AuthInvoicesGet200ResponseInvoicesInner {
    return AuthInvoicesGet200ResponseInvoicesInnerToJSONTyped(json, false);
}

export function AuthInvoicesGet200ResponseInvoicesInnerToJSONTyped(value?: AuthInvoicesGet200ResponseInvoicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'],
        'status': value['status'],
        'paid': value['paid'],
        'invoiceNumber': value['invoiceNumber'],
        'totalAmount': value['totalAmount'],
        'currency': value['currency'],
        'dueAmount': value['dueAmount'],
        'billingReason': value['billingReason'],
        'isInvoiceGenerated': value['isInvoiceGenerated'],
    };
}

