/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateStorageConfigRequestStorageConfig } from './CreateStorageConfigRequestStorageConfig';
import {
    CreateStorageConfigRequestStorageConfigFromJSON,
    CreateStorageConfigRequestStorageConfigFromJSONTyped,
    CreateStorageConfigRequestStorageConfigToJSON,
    CreateStorageConfigRequestStorageConfigToJSONTyped,
} from './CreateStorageConfigRequestStorageConfig';

/**
 * 
 * @export
 * @interface CreateStorageConfigRequest
 */
export interface CreateStorageConfigRequest {
    /**
     * Unique key for this storage configuration
     * @type {string}
     * @memberof CreateStorageConfigRequest
     */
    storageKey: string;
    /**
     * 
     * @type {CreateStorageConfigRequestStorageConfig}
     * @memberof CreateStorageConfigRequest
     */
    storageConfig: CreateStorageConfigRequestStorageConfig;
}

/**
 * Check if a given object implements the CreateStorageConfigRequest interface.
 */
export function instanceOfCreateStorageConfigRequest(value: object): value is CreateStorageConfigRequest {
    if (!('storageKey' in value) || value['storageKey'] === undefined) return false;
    if (!('storageConfig' in value) || value['storageConfig'] === undefined) return false;
    return true;
}

export function CreateStorageConfigRequestFromJSON(json: any): CreateStorageConfigRequest {
    return CreateStorageConfigRequestFromJSONTyped(json, false);
}

export function CreateStorageConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStorageConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storageKey': json['storageKey'],
        'storageConfig': CreateStorageConfigRequestStorageConfigFromJSON(json['storageConfig']),
    };
}

export function CreateStorageConfigRequestToJSON(json: any): CreateStorageConfigRequest {
    return CreateStorageConfigRequestToJSONTyped(json, false);
}

export function CreateStorageConfigRequestToJSONTyped(value?: CreateStorageConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageKey': value['storageKey'],
        'storageConfig': CreateStorageConfigRequestStorageConfigToJSON(value['storageConfig']),
    };
}

