/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiKey200ResponseData
 */
export interface CreateApiKey200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof CreateApiKey200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiKey200ResponseData
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiKey200ResponseData
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiKey200ResponseData
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateApiKey200ResponseData
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateApiKey200ResponseData
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the CreateApiKey200ResponseData interface.
 */
export function instanceOfCreateApiKey200ResponseData(value: object): value is CreateApiKey200ResponseData {
    return true;
}

export function CreateApiKey200ResponseDataFromJSON(json: any): CreateApiKey200ResponseData {
    return CreateApiKey200ResponseDataFromJSONTyped(json, false);
}

export function CreateApiKey200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKey200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'key': json['key'] == null ? undefined : json['key'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function CreateApiKey200ResponseDataToJSON(json: any): CreateApiKey200ResponseData {
    return CreateApiKey200ResponseDataToJSONTyped(json, false);
}

export function CreateApiKey200ResponseDataToJSONTyped(value?: CreateApiKey200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'key': value['key'],
        'description': value['description'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'],
    };
}

