/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTemplateRequest
 */
export interface CreateTemplateRequest {
    /**
     * HTML template content
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    templateContent: string;
    /**
     * Name of the template
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    templateName?: string;
    /**
     * Page size (e.g., A4, Letter, 100mm|100mm, 10in|10in). Defaults to A4
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    templateSize?: string;
}

/**
 * Check if a given object implements the CreateTemplateRequest interface.
 */
export function instanceOfCreateTemplateRequest(value: object): value is CreateTemplateRequest {
    if (!('templateContent' in value) || value['templateContent'] === undefined) return false;
    return true;
}

export function CreateTemplateRequestFromJSON(json: any): CreateTemplateRequest {
    return CreateTemplateRequestFromJSONTyped(json, false);
}

export function CreateTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateContent': json['templateContent'],
        'templateName': json['templateName'] == null ? undefined : json['templateName'],
        'templateSize': json['templateSize'] == null ? undefined : json['templateSize'],
    };
}

export function CreateTemplateRequestToJSON(json: any): CreateTemplateRequest {
    return CreateTemplateRequestToJSONTyped(json, false);
}

export function CreateTemplateRequestToJSONTyped(value?: CreateTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templateContent': value['templateContent'],
        'templateName': value['templateName'],
        'templateSize': value['templateSize'],
    };
}

