/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateApiKey200ResponseData } from './CreateApiKey200ResponseData';
import {
    CreateApiKey200ResponseDataFromJSON,
    CreateApiKey200ResponseDataFromJSONTyped,
    CreateApiKey200ResponseDataToJSON,
    CreateApiKey200ResponseDataToJSONTyped,
} from './CreateApiKey200ResponseData';

/**
 * 
 * @export
 * @interface CreateApiKey200Response
 */
export interface CreateApiKey200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateApiKey200Response
     */
    success?: boolean;
    /**
     * 
     * @type {CreateApiKey200ResponseData}
     * @memberof CreateApiKey200Response
     */
    data?: CreateApiKey200ResponseData;
}

/**
 * Check if a given object implements the CreateApiKey200Response interface.
 */
export function instanceOfCreateApiKey200Response(value: object): value is CreateApiKey200Response {
    return true;
}

export function CreateApiKey200ResponseFromJSON(json: any): CreateApiKey200Response {
    return CreateApiKey200ResponseFromJSONTyped(json, false);
}

export function CreateApiKey200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKey200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : CreateApiKey200ResponseDataFromJSON(json['data']),
    };
}

export function CreateApiKey200ResponseToJSON(json: any): CreateApiKey200Response {
    return CreateApiKey200ResponseToJSONTyped(json, false);
}

export function CreateApiKey200ResponseToJSONTyped(value?: CreateApiKey200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CreateApiKey200ResponseDataToJSON(value['data']),
    };
}

