/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTemplates200ResponseTemplatesInner } from './ListTemplates200ResponseTemplatesInner';
import {
    ListTemplates200ResponseTemplatesInnerFromJSON,
    ListTemplates200ResponseTemplatesInnerFromJSONTyped,
    ListTemplates200ResponseTemplatesInnerToJSON,
    ListTemplates200ResponseTemplatesInnerToJSONTyped,
} from './ListTemplates200ResponseTemplatesInner';

/**
 * 
 * @export
 * @interface CreateTemplate200Response
 */
export interface CreateTemplate200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateTemplate200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateTemplate200Response
     */
    message?: string;
    /**
     * 
     * @type {ListTemplates200ResponseTemplatesInner}
     * @memberof CreateTemplate200Response
     */
    data?: ListTemplates200ResponseTemplatesInner;
}

/**
 * Check if a given object implements the CreateTemplate200Response interface.
 */
export function instanceOfCreateTemplate200Response(value: object): value is CreateTemplate200Response {
    return true;
}

export function CreateTemplate200ResponseFromJSON(json: any): CreateTemplate200Response {
    return CreateTemplate200ResponseFromJSONTyped(json, false);
}

export function CreateTemplate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTemplate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ListTemplates200ResponseTemplatesInnerFromJSON(json['data']),
    };
}

export function CreateTemplate200ResponseToJSON(json: any): CreateTemplate200Response {
    return CreateTemplate200ResponseToJSONTyped(json, false);
}

export function CreateTemplate200ResponseToJSONTyped(value?: CreateTemplate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': ListTemplates200ResponseTemplatesInnerToJSON(value['data']),
    };
}

