/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTemplate400Response
 */
export interface CreateTemplate400Response {
    /**
     * 
     * @type {string}
     * @memberof CreateTemplate400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the CreateTemplate400Response interface.
 */
export function instanceOfCreateTemplate400Response(value: object): value is CreateTemplate400Response {
    return true;
}

export function CreateTemplate400ResponseFromJSON(json: any): CreateTemplate400Response {
    return CreateTemplate400ResponseFromJSONTyped(json, false);
}

export function CreateTemplate400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTemplate400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CreateTemplate400ResponseToJSON(json: any): CreateTemplate400Response {
    return CreateTemplate400ResponseToJSONTyped(json, false);
}

export function CreateTemplate400ResponseToJSONTyped(value?: CreateTemplate400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

