/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStorageConfig400Response
 */
export interface CreateStorageConfig400Response {
    /**
     * 
     * @type {string}
     * @memberof CreateStorageConfig400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the CreateStorageConfig400Response interface.
 */
export function instanceOfCreateStorageConfig400Response(value: object): value is CreateStorageConfig400Response {
    return true;
}

export function CreateStorageConfig400ResponseFromJSON(json: any): CreateStorageConfig400Response {
    return CreateStorageConfig400ResponseFromJSONTyped(json, false);
}

export function CreateStorageConfig400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStorageConfig400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CreateStorageConfig400ResponseToJSON(json: any): CreateStorageConfig400Response {
    return CreateStorageConfig400ResponseToJSONTyped(json, false);
}

export function CreateStorageConfig400ResponseToJSONTyped(value?: CreateStorageConfig400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

