/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Storage configuration object
 * @export
 * @interface CreateStorageConfigRequestStorageConfig
 */
export interface CreateStorageConfigRequestStorageConfig {
    /**
     * Type of storage
     * @type {string}
     * @memberof CreateStorageConfigRequestStorageConfig
     */
    storageType?: CreateStorageConfigRequestStorageConfigStorageTypeEnum;
}


/**
 * @export
 */
export const CreateStorageConfigRequestStorageConfigStorageTypeEnum = {
    S3: 's3',
    AzureBlob: 'azureBlob',
    Ftp: 'ftp'
} as const;
export type CreateStorageConfigRequestStorageConfigStorageTypeEnum = typeof CreateStorageConfigRequestStorageConfigStorageTypeEnum[keyof typeof CreateStorageConfigRequestStorageConfigStorageTypeEnum];


/**
 * Check if a given object implements the CreateStorageConfigRequestStorageConfig interface.
 */
export function instanceOfCreateStorageConfigRequestStorageConfig(value: object): value is CreateStorageConfigRequestStorageConfig {
    return true;
}

export function CreateStorageConfigRequestStorageConfigFromJSON(json: any): CreateStorageConfigRequestStorageConfig {
    return CreateStorageConfigRequestStorageConfigFromJSONTyped(json, false);
}

export function CreateStorageConfigRequestStorageConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStorageConfigRequestStorageConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'storageType': json['storageType'] == null ? undefined : json['storageType'],
    };
}

export function CreateStorageConfigRequestStorageConfigToJSON(json: any): CreateStorageConfigRequestStorageConfig {
    return CreateStorageConfigRequestStorageConfigToJSONTyped(json, false);
}

export function CreateStorageConfigRequestStorageConfigToJSONTyped(value?: CreateStorageConfigRequestStorageConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageType': value['storageType'],
    };
}

