/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateDocument200Response
 */
export interface GenerateDocument200Response {
    /**
     * Storage metadata if uploaded
     * @type {object}
     * @memberof GenerateDocument200Response
     */
    meta?: object;
    /**
     * Base64 encoded PDF if returnFile is true
     * @type {string}
     * @memberof GenerateDocument200Response
     */
    data?: string;
}

/**
 * Check if a given object implements the GenerateDocument200Response interface.
 */
export function instanceOfGenerateDocument200Response(value: object): value is GenerateDocument200Response {
    return true;
}

export function GenerateDocument200ResponseFromJSON(json: any): GenerateDocument200Response {
    return GenerateDocument200ResponseFromJSONTyped(json, false);
}

export function GenerateDocument200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateDocument200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : json['meta'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function GenerateDocument200ResponseToJSON(json: any): GenerateDocument200Response {
    return GenerateDocument200ResponseToJSONTyped(json, false);
}

export function GenerateDocument200ResponseToJSONTyped(value?: GenerateDocument200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': value['meta'],
        'data': value['data'],
    };
}

