/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateTemplateFromPromptRequest
 */
export interface GenerateTemplateFromPromptRequest {
    /**
     * Description of the template you want to generate
     * @type {string}
     * @memberof GenerateTemplateFromPromptRequest
     */
    prompt: string;
    /**
     * Data fields that will be injected into the template (keys will be used as placeholders)
     * @type {object}
     * @memberof GenerateTemplateFromPromptRequest
     */
    params?: object;
    /**
     * Name for the generated template
     * @type {string}
     * @memberof GenerateTemplateFromPromptRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the GenerateTemplateFromPromptRequest interface.
 */
export function instanceOfGenerateTemplateFromPromptRequest(value: object): value is GenerateTemplateFromPromptRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GenerateTemplateFromPromptRequestFromJSON(json: any): GenerateTemplateFromPromptRequest {
    return GenerateTemplateFromPromptRequestFromJSONTyped(json, false);
}

export function GenerateTemplateFromPromptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTemplateFromPromptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'params': json['params'] == null ? undefined : json['params'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GenerateTemplateFromPromptRequestToJSON(json: any): GenerateTemplateFromPromptRequest {
    return GenerateTemplateFromPromptRequestToJSONTyped(json, false);
}

export function GenerateTemplateFromPromptRequestToJSONTyped(value?: GenerateTemplateFromPromptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'params': value['params'],
        'name': value['name'],
    };
}

