/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Storage configuration for uploading the PDF
 * @export
 * @interface GenerateDocumentRequestStorage
 */
export interface GenerateDocumentRequestStorage {
    /**
     * Enable storage upload
     * @type {boolean}
     * @memberof GenerateDocumentRequestStorage
     */
    enabled?: boolean;
    /**
     * Storage configuration key
     * @type {string}
     * @memberof GenerateDocumentRequestStorage
     */
    storageKey?: string;
}

/**
 * Check if a given object implements the GenerateDocumentRequestStorage interface.
 */
export function instanceOfGenerateDocumentRequestStorage(value: object): value is GenerateDocumentRequestStorage {
    return true;
}

export function GenerateDocumentRequestStorageFromJSON(json: any): GenerateDocumentRequestStorage {
    return GenerateDocumentRequestStorageFromJSONTyped(json, false);
}

export function GenerateDocumentRequestStorageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateDocumentRequestStorage {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'storageKey': json['storageKey'] == null ? undefined : json['storageKey'],
    };
}

export function GenerateDocumentRequestStorageToJSON(json: any): GenerateDocumentRequestStorage {
    return GenerateDocumentRequestStorageToJSONTyped(json, false);
}

export function GenerateDocumentRequestStorageToJSONTyped(value?: GenerateDocumentRequestStorage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'storageKey': value['storageKey'],
    };
}

