/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateTemplateFromPdf500Response
 */
export interface GenerateTemplateFromPdf500Response {
    /**
     * 
     * @type {string}
     * @memberof GenerateTemplateFromPdf500Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateTemplateFromPdf500Response
     */
    details?: string;
}

/**
 * Check if a given object implements the GenerateTemplateFromPdf500Response interface.
 */
export function instanceOfGenerateTemplateFromPdf500Response(value: object): value is GenerateTemplateFromPdf500Response {
    return true;
}

export function GenerateTemplateFromPdf500ResponseFromJSON(json: any): GenerateTemplateFromPdf500Response {
    return GenerateTemplateFromPdf500ResponseFromJSONTyped(json, false);
}

export function GenerateTemplateFromPdf500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTemplateFromPdf500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function GenerateTemplateFromPdf500ResponseToJSON(json: any): GenerateTemplateFromPdf500Response {
    return GenerateTemplateFromPdf500ResponseToJSONTyped(json, false);
}

export function GenerateTemplateFromPdf500ResponseToJSONTyped(value?: GenerateTemplateFromPdf500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'details': value['details'],
    };
}

