/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenerateDocumentRequestStorage } from './GenerateDocumentRequestStorage';
import {
    GenerateDocumentRequestStorageFromJSON,
    GenerateDocumentRequestStorageFromJSONTyped,
    GenerateDocumentRequestStorageToJSON,
    GenerateDocumentRequestStorageToJSONTyped,
} from './GenerateDocumentRequestStorage';

/**
 * 
 * @export
 * @interface GenerateDocumentRequest
 */
export interface GenerateDocumentRequest {
    /**
     * ID of stored template to use
     * @type {string}
     * @memberof GenerateDocumentRequest
     */
    templateId?: string;
    /**
     * Alternatively, string of the template to use
     * @type {string}
     * @memberof GenerateDocumentRequest
     */
    html?: string;
    /**
     * With html, size of the document to use
     * @type {string}
     * @memberof GenerateDocumentRequest
     */
    size?: string;
    /**
     * With html, orientation of the document to use
     * @type {string}
     * @memberof GenerateDocumentRequest
     */
    orientation?: string;
    /**
     * Data to inject into the template
     * @type {object}
     * @memberof GenerateDocumentRequest
     */
    data?: object;
    /**
     * 
     * @type {GenerateDocumentRequestStorage}
     * @memberof GenerateDocumentRequest
     */
    storage?: GenerateDocumentRequestStorage;
    /**
     * If true, return PDF in response (default: true)
     * @type {boolean}
     * @memberof GenerateDocumentRequest
     */
    returnFile?: boolean;
    /**
     * If true, add SECRET watermark and charge 0 credits
     * @type {boolean}
     * @memberof GenerateDocumentRequest
     */
    sandbox?: boolean;
}

/**
 * Check if a given object implements the GenerateDocumentRequest interface.
 */
export function instanceOfGenerateDocumentRequest(value: object): value is GenerateDocumentRequest {
    return true;
}

export function GenerateDocumentRequestFromJSON(json: any): GenerateDocumentRequest {
    return GenerateDocumentRequestFromJSONTyped(json, false);
}

export function GenerateDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateDocumentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['templateId'] == null ? undefined : json['templateId'],
        'html': json['html'] == null ? undefined : json['html'],
        'size': json['size'] == null ? undefined : json['size'],
        'orientation': json['orientation'] == null ? undefined : json['orientation'],
        'data': json['data'] == null ? undefined : json['data'],
        'storage': json['storage'] == null ? undefined : GenerateDocumentRequestStorageFromJSON(json['storage']),
        'returnFile': json['returnFile'] == null ? undefined : json['returnFile'],
        'sandbox': json['sandbox'] == null ? undefined : json['sandbox'],
    };
}

export function GenerateDocumentRequestToJSON(json: any): GenerateDocumentRequest {
    return GenerateDocumentRequestToJSONTyped(json, false);
}

export function GenerateDocumentRequestToJSONTyped(value?: GenerateDocumentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templateId': value['templateId'],
        'html': value['html'],
        'size': value['size'],
        'orientation': value['orientation'],
        'data': value['data'],
        'storage': GenerateDocumentRequestStorageToJSON(value['storage']),
        'returnFile': value['returnFile'],
        'sandbox': value['sandbox'],
    };
}

