/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBillingPortal200Response
 */
export interface GetBillingPortal200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetBillingPortal200Response
     */
    success?: boolean;
    /**
     * URL to access the Polar customer portal
     * @type {string}
     * @memberof GetBillingPortal200Response
     */
    portalUrl?: string;
}

/**
 * Check if a given object implements the GetBillingPortal200Response interface.
 */
export function instanceOfGetBillingPortal200Response(value: object): value is GetBillingPortal200Response {
    return true;
}

export function GetBillingPortal200ResponseFromJSON(json: any): GetBillingPortal200Response {
    return GetBillingPortal200ResponseFromJSONTyped(json, false);
}

export function GetBillingPortal200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingPortal200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'portalUrl': json['portalUrl'] == null ? undefined : json['portalUrl'],
    };
}

export function GetBillingPortal200ResponseToJSON(json: any): GetBillingPortal200Response {
    return GetBillingPortal200ResponseToJSONTyped(json, false);
}

export function GetBillingPortal200ResponseToJSONTyped(value?: GetBillingPortal200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'portalUrl': value['portalUrl'],
    };
}

