/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCredits200Response
 */
export interface GetCredits200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetCredits200Response
     */
    success?: boolean;
    /**
     * Number of credits used this month
     * @type {number}
     * @memberof GetCredits200Response
     */
    creditsUsed?: number;
    /**
     * Number of free credits remaining
     * @type {number}
     * @memberof GetCredits200Response
     */
    creditsRemaining?: number;
    /**
     * Whether user has an active subscription
     * @type {boolean}
     * @memberof GetCredits200Response
     */
    isSubscribed?: boolean;
    /**
     * Whether user needs to subscribe to continue
     * @type {boolean}
     * @memberof GetCredits200Response
     */
    needsSubscription?: boolean;
}

/**
 * Check if a given object implements the GetCredits200Response interface.
 */
export function instanceOfGetCredits200Response(value: object): value is GetCredits200Response {
    return true;
}

export function GetCredits200ResponseFromJSON(json: any): GetCredits200Response {
    return GetCredits200ResponseFromJSONTyped(json, false);
}

export function GetCredits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCredits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'creditsUsed': json['creditsUsed'] == null ? undefined : json['creditsUsed'],
        'creditsRemaining': json['creditsRemaining'] == null ? undefined : json['creditsRemaining'],
        'isSubscribed': json['isSubscribed'] == null ? undefined : json['isSubscribed'],
        'needsSubscription': json['needsSubscription'] == null ? undefined : json['needsSubscription'],
    };
}

export function GetCredits200ResponseToJSON(json: any): GetCredits200Response {
    return GetCredits200ResponseToJSONTyped(json, false);
}

export function GetCredits200ResponseToJSONTyped(value?: GetCredits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'creditsUsed': value['creditsUsed'],
        'creditsRemaining': value['creditsRemaining'],
        'isSubscribed': value['isSubscribed'],
        'needsSubscription': value['needsSubscription'],
    };
}

