/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetGenerationStats200ResponseStats } from './GetGenerationStats200ResponseStats';
import {
    GetGenerationStats200ResponseStatsFromJSON,
    GetGenerationStats200ResponseStatsFromJSONTyped,
    GetGenerationStats200ResponseStatsToJSON,
    GetGenerationStats200ResponseStatsToJSONTyped,
} from './GetGenerationStats200ResponseStats';

/**
 * 
 * @export
 * @interface GetGenerationStats200Response
 */
export interface GetGenerationStats200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetGenerationStats200Response
     */
    success?: boolean;
    /**
     * 
     * @type {GetGenerationStats200ResponseStats}
     * @memberof GetGenerationStats200Response
     */
    stats?: GetGenerationStats200ResponseStats;
}

/**
 * Check if a given object implements the GetGenerationStats200Response interface.
 */
export function instanceOfGetGenerationStats200Response(value: object): value is GetGenerationStats200Response {
    return true;
}

export function GetGenerationStats200ResponseFromJSON(json: any): GetGenerationStats200Response {
    return GetGenerationStats200ResponseFromJSONTyped(json, false);
}

export function GetGenerationStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGenerationStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'stats': json['stats'] == null ? undefined : GetGenerationStats200ResponseStatsFromJSON(json['stats']),
    };
}

export function GetGenerationStats200ResponseToJSON(json: any): GetGenerationStats200Response {
    return GetGenerationStats200ResponseToJSONTyped(json, false);
}

export function GetGenerationStats200ResponseToJSONTyped(value?: GetGenerationStats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'stats': GetGenerationStats200ResponseStatsToJSON(value['stats']),
    };
}

