/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGenerationStats200ResponseStats
 */
export interface GetGenerationStats200ResponseStats {
    /**
     * Total number of PDFs created
     * @type {number}
     * @memberof GetGenerationStats200ResponseStats
     */
    totalPdfsCreated?: number;
    /**
     * Number of successful PDF generations
     * @type {number}
     * @memberof GetGenerationStats200ResponseStats
     */
    totalSuccessful?: number;
    /**
     * Number of failed PDF generations
     * @type {number}
     * @memberof GetGenerationStats200ResponseStats
     */
    totalFailed?: number;
}

/**
 * Check if a given object implements the GetGenerationStats200ResponseStats interface.
 */
export function instanceOfGetGenerationStats200ResponseStats(value: object): value is GetGenerationStats200ResponseStats {
    return true;
}

export function GetGenerationStats200ResponseStatsFromJSON(json: any): GetGenerationStats200ResponseStats {
    return GetGenerationStats200ResponseStatsFromJSONTyped(json, false);
}

export function GetGenerationStats200ResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGenerationStats200ResponseStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPdfsCreated': json['totalPdfsCreated'] == null ? undefined : json['totalPdfsCreated'],
        'totalSuccessful': json['totalSuccessful'] == null ? undefined : json['totalSuccessful'],
        'totalFailed': json['totalFailed'] == null ? undefined : json['totalFailed'],
    };
}

export function GetGenerationStats200ResponseStatsToJSON(json: any): GetGenerationStats200ResponseStats {
    return GetGenerationStats200ResponseStatsToJSONTyped(json, false);
}

export function GetGenerationStats200ResponseStatsToJSONTyped(value?: GetGenerationStats200ResponseStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPdfsCreated': value['totalPdfsCreated'],
        'totalSuccessful': value['totalSuccessful'],
        'totalFailed': value['totalFailed'],
    };
}

