/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetMe200ResponseUser } from './GetMe200ResponseUser';
import {
    GetMe200ResponseUserFromJSON,
    GetMe200ResponseUserFromJSONTyped,
    GetMe200ResponseUserToJSON,
    GetMe200ResponseUserToJSONTyped,
} from './GetMe200ResponseUser';
import type { GetMe200ResponseBilling } from './GetMe200ResponseBilling';
import {
    GetMe200ResponseBillingFromJSON,
    GetMe200ResponseBillingFromJSONTyped,
    GetMe200ResponseBillingToJSON,
    GetMe200ResponseBillingToJSONTyped,
} from './GetMe200ResponseBilling';

/**
 * 
 * @export
 * @interface GetMe200Response
 */
export interface GetMe200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetMe200Response
     */
    success?: boolean;
    /**
     * 
     * @type {GetMe200ResponseUser}
     * @memberof GetMe200Response
     */
    user?: GetMe200ResponseUser;
    /**
     * 
     * @type {GetMe200ResponseBilling}
     * @memberof GetMe200Response
     */
    billing?: GetMe200ResponseBilling;
}

/**
 * Check if a given object implements the GetMe200Response interface.
 */
export function instanceOfGetMe200Response(value: object): value is GetMe200Response {
    return true;
}

export function GetMe200ResponseFromJSON(json: any): GetMe200Response {
    return GetMe200ResponseFromJSONTyped(json, false);
}

export function GetMe200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMe200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'user': json['user'] == null ? undefined : GetMe200ResponseUserFromJSON(json['user']),
        'billing': json['billing'] == null ? undefined : GetMe200ResponseBillingFromJSON(json['billing']),
    };
}

export function GetMe200ResponseToJSON(json: any): GetMe200Response {
    return GetMe200ResponseToJSONTyped(json, false);
}

export function GetMe200ResponseToJSONTyped(value?: GetMe200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'user': GetMe200ResponseUserToJSON(value['user']),
        'billing': GetMe200ResponseBillingToJSON(value['billing']),
    };
}

