/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRecentActivity200ResponseRecentActivitiesInner
 */
export interface GetRecentActivity200ResponseRecentActivitiesInner {
    /**
     * 
     * @type {string}
     * @memberof GetRecentActivity200ResponseRecentActivitiesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetRecentActivity200ResponseRecentActivitiesInner
     */
    activityType?: string;
    /**
     * 
     * @type {string}
     * @memberof GetRecentActivity200ResponseRecentActivitiesInner
     */
    entityType?: string;
    /**
     * 
     * @type {string}
     * @memberof GetRecentActivity200ResponseRecentActivitiesInner
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetRecentActivity200ResponseRecentActivitiesInner
     */
    entityName?: string;
    /**
     * 
     * @type {object}
     * @memberof GetRecentActivity200ResponseRecentActivitiesInner
     */
    metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof GetRecentActivity200ResponseRecentActivitiesInner
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the GetRecentActivity200ResponseRecentActivitiesInner interface.
 */
export function instanceOfGetRecentActivity200ResponseRecentActivitiesInner(value: object): value is GetRecentActivity200ResponseRecentActivitiesInner {
    return true;
}

export function GetRecentActivity200ResponseRecentActivitiesInnerFromJSON(json: any): GetRecentActivity200ResponseRecentActivitiesInner {
    return GetRecentActivity200ResponseRecentActivitiesInnerFromJSONTyped(json, false);
}

export function GetRecentActivity200ResponseRecentActivitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRecentActivity200ResponseRecentActivitiesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'activityType': json['activityType'] == null ? undefined : json['activityType'],
        'entityType': json['entityType'] == null ? undefined : json['entityType'],
        'entityId': json['entityId'] == null ? undefined : json['entityId'],
        'entityName': json['entityName'] == null ? undefined : json['entityName'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function GetRecentActivity200ResponseRecentActivitiesInnerToJSON(json: any): GetRecentActivity200ResponseRecentActivitiesInner {
    return GetRecentActivity200ResponseRecentActivitiesInnerToJSONTyped(json, false);
}

export function GetRecentActivity200ResponseRecentActivitiesInnerToJSONTyped(value?: GetRecentActivity200ResponseRecentActivitiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'activityType': value['activityType'],
        'entityType': value['entityType'],
        'entityId': value['entityId'],
        'entityName': value['entityName'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'],
    };
}

