/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetRecentActivity200ResponseStats } from './GetRecentActivity200ResponseStats';
import {
    GetRecentActivity200ResponseStatsFromJSON,
    GetRecentActivity200ResponseStatsFromJSONTyped,
    GetRecentActivity200ResponseStatsToJSON,
    GetRecentActivity200ResponseStatsToJSONTyped,
} from './GetRecentActivity200ResponseStats';
import type { GetRecentActivity200ResponseRecentActivitiesInner } from './GetRecentActivity200ResponseRecentActivitiesInner';
import {
    GetRecentActivity200ResponseRecentActivitiesInnerFromJSON,
    GetRecentActivity200ResponseRecentActivitiesInnerFromJSONTyped,
    GetRecentActivity200ResponseRecentActivitiesInnerToJSON,
    GetRecentActivity200ResponseRecentActivitiesInnerToJSONTyped,
} from './GetRecentActivity200ResponseRecentActivitiesInner';

/**
 * 
 * @export
 * @interface GetRecentActivity200Response
 */
export interface GetRecentActivity200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetRecentActivity200Response
     */
    success?: boolean;
    /**
     * 
     * @type {GetRecentActivity200ResponseStats}
     * @memberof GetRecentActivity200Response
     */
    stats?: GetRecentActivity200ResponseStats;
    /**
     * 
     * @type {Array<GetRecentActivity200ResponseRecentActivitiesInner>}
     * @memberof GetRecentActivity200Response
     */
    recentActivities?: Array<GetRecentActivity200ResponseRecentActivitiesInner>;
}

/**
 * Check if a given object implements the GetRecentActivity200Response interface.
 */
export function instanceOfGetRecentActivity200Response(value: object): value is GetRecentActivity200Response {
    return true;
}

export function GetRecentActivity200ResponseFromJSON(json: any): GetRecentActivity200Response {
    return GetRecentActivity200ResponseFromJSONTyped(json, false);
}

export function GetRecentActivity200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRecentActivity200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'stats': json['stats'] == null ? undefined : GetRecentActivity200ResponseStatsFromJSON(json['stats']),
        'recentActivities': json['recentActivities'] == null ? undefined : ((json['recentActivities'] as Array<any>).map(GetRecentActivity200ResponseRecentActivitiesInnerFromJSON)),
    };
}

export function GetRecentActivity200ResponseToJSON(json: any): GetRecentActivity200Response {
    return GetRecentActivity200ResponseToJSONTyped(json, false);
}

export function GetRecentActivity200ResponseToJSONTyped(value?: GetRecentActivity200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'stats': GetRecentActivity200ResponseStatsToJSON(value['stats']),
        'recentActivities': value['recentActivities'] == null ? undefined : ((value['recentActivities'] as Array<any>).map(GetRecentActivity200ResponseRecentActivitiesInnerToJSON)),
    };
}

