/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetRecentActivity200ResponseStats
 */
export interface GetRecentActivity200ResponseStats {
    /**
     * 
     * @type {number}
     * @memberof GetRecentActivity200ResponseStats
     */
    totalTemplates?: number;
    /**
     * 
     * @type {number}
     * @memberof GetRecentActivity200ResponseStats
     */
    totalActiveApiKeys?: number;
    /**
     * 
     * @type {number}
     * @memberof GetRecentActivity200ResponseStats
     */
    totalGeneratedPdfs?: number;
    /**
     * 
     * @type {number}
     * @memberof GetRecentActivity200ResponseStats
     */
    generatedPdfsLast30Days?: number;
    /**
     * 
     * @type {number}
     * @memberof GetRecentActivity200ResponseStats
     */
    totalCreditsUsed?: number;
    /**
     * Credits used in the current billing month
     * @type {number}
     * @memberof GetRecentActivity200ResponseStats
     */
    creditsUsedCurrentMonth?: number;
}

/**
 * Check if a given object implements the GetRecentActivity200ResponseStats interface.
 */
export function instanceOfGetRecentActivity200ResponseStats(value: object): value is GetRecentActivity200ResponseStats {
    return true;
}

export function GetRecentActivity200ResponseStatsFromJSON(json: any): GetRecentActivity200ResponseStats {
    return GetRecentActivity200ResponseStatsFromJSONTyped(json, false);
}

export function GetRecentActivity200ResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRecentActivity200ResponseStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTemplates': json['totalTemplates'] == null ? undefined : json['totalTemplates'],
        'totalActiveApiKeys': json['totalActiveApiKeys'] == null ? undefined : json['totalActiveApiKeys'],
        'totalGeneratedPdfs': json['totalGeneratedPdfs'] == null ? undefined : json['totalGeneratedPdfs'],
        'generatedPdfsLast30Days': json['generatedPdfsLast30Days'] == null ? undefined : json['generatedPdfsLast30Days'],
        'totalCreditsUsed': json['totalCreditsUsed'] == null ? undefined : json['totalCreditsUsed'],
        'creditsUsedCurrentMonth': json['creditsUsedCurrentMonth'] == null ? undefined : json['creditsUsedCurrentMonth'],
    };
}

export function GetRecentActivity200ResponseStatsToJSON(json: any): GetRecentActivity200ResponseStats {
    return GetRecentActivity200ResponseStatsToJSONTyped(json, false);
}

export function GetRecentActivity200ResponseStatsToJSONTyped(value?: GetRecentActivity200ResponseStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalTemplates': value['totalTemplates'],
        'totalActiveApiKeys': value['totalActiveApiKeys'],
        'totalGeneratedPdfs': value['totalGeneratedPdfs'],
        'generatedPdfsLast30Days': value['generatedPdfsLast30Days'],
        'totalCreditsUsed': value['totalCreditsUsed'],
        'creditsUsedCurrentMonth': value['creditsUsedCurrentMonth'],
    };
}

