/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStorageConfig200Response
 */
export interface GetStorageConfig200Response {
    /**
     * 
     * @type {object}
     * @memberof GetStorageConfig200Response
     */
    config?: object;
    /**
     * 
     * @type {string}
     * @memberof GetStorageConfig200Response
     */
    storageKey?: string;
}

/**
 * Check if a given object implements the GetStorageConfig200Response interface.
 */
export function instanceOfGetStorageConfig200Response(value: object): value is GetStorageConfig200Response {
    return true;
}

export function GetStorageConfig200ResponseFromJSON(json: any): GetStorageConfig200Response {
    return GetStorageConfig200ResponseFromJSONTyped(json, false);
}

export function GetStorageConfig200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStorageConfig200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
        'storageKey': json['storageKey'] == null ? undefined : json['storageKey'],
    };
}

export function GetStorageConfig200ResponseToJSON(json: any): GetStorageConfig200Response {
    return GetStorageConfig200ResponseToJSONTyped(json, false);
}

export function GetStorageConfig200ResponseToJSONTyped(value?: GetStorageConfig200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'storageKey': value['storageKey'],
    };
}

