/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUsageStats200ResponseStatsInner } from './GetUsageStats200ResponseStatsInner';
import {
    GetUsageStats200ResponseStatsInnerFromJSON,
    GetUsageStats200ResponseStatsInnerFromJSONTyped,
    GetUsageStats200ResponseStatsInnerToJSON,
    GetUsageStats200ResponseStatsInnerToJSONTyped,
} from './GetUsageStats200ResponseStatsInner';

/**
 * 
 * @export
 * @interface GetUsageStats200Response
 */
export interface GetUsageStats200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetUsageStats200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<GetUsageStats200ResponseStatsInner>}
     * @memberof GetUsageStats200Response
     */
    stats?: Array<GetUsageStats200ResponseStatsInner>;
}

/**
 * Check if a given object implements the GetUsageStats200Response interface.
 */
export function instanceOfGetUsageStats200Response(value: object): value is GetUsageStats200Response {
    return true;
}

export function GetUsageStats200ResponseFromJSON(json: any): GetUsageStats200Response {
    return GetUsageStats200ResponseFromJSONTyped(json, false);
}

export function GetUsageStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsageStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'stats': json['stats'] == null ? undefined : ((json['stats'] as Array<any>).map(GetUsageStats200ResponseStatsInnerFromJSON)),
    };
}

export function GetUsageStats200ResponseToJSON(json: any): GetUsageStats200Response {
    return GetUsageStats200ResponseToJSONTyped(json, false);
}

export function GetUsageStats200ResponseToJSONTyped(value?: GetUsageStats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'stats': value['stats'] == null ? undefined : ((value['stats'] as Array<any>).map(GetUsageStats200ResponseStatsInnerToJSON)),
    };
}

