/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubCallback200ResponseUser } from './GithubCallback200ResponseUser';
import {
    GithubCallback200ResponseUserFromJSON,
    GithubCallback200ResponseUserFromJSONTyped,
    GithubCallback200ResponseUserToJSON,
    GithubCallback200ResponseUserToJSONTyped,
} from './GithubCallback200ResponseUser';

/**
 * 
 * @export
 * @interface GithubCallback200Response
 */
export interface GithubCallback200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GithubCallback200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GithubCallback200Response
     */
    message?: string;
    /**
     * 
     * @type {GithubCallback200ResponseUser}
     * @memberof GithubCallback200Response
     */
    user?: GithubCallback200ResponseUser;
    /**
     * JWT token for authentication
     * @type {string}
     * @memberof GithubCallback200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the GithubCallback200Response interface.
 */
export function instanceOfGithubCallback200Response(value: object): value is GithubCallback200Response {
    return true;
}

export function GithubCallback200ResponseFromJSON(json: any): GithubCallback200Response {
    return GithubCallback200ResponseFromJSONTyped(json, false);
}

export function GithubCallback200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubCallback200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'user': json['user'] == null ? undefined : GithubCallback200ResponseUserFromJSON(json['user']),
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function GithubCallback200ResponseToJSON(json: any): GithubCallback200Response {
    return GithubCallback200ResponseToJSONTyped(json, false);
}

export function GithubCallback200ResponseToJSONTyped(value?: GithubCallback200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'user': GithubCallback200ResponseUserToJSON(value['user']),
        'token': value['token'],
    };
}

