/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubCallback200ResponseUser
 */
export interface GithubCallback200ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof GithubCallback200ResponseUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubCallback200ResponseUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubCallback200ResponseUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubCallback200ResponseUser
     */
    githubId?: string;
}

/**
 * Check if a given object implements the GithubCallback200ResponseUser interface.
 */
export function instanceOfGithubCallback200ResponseUser(value: object): value is GithubCallback200ResponseUser {
    return true;
}

export function GithubCallback200ResponseUserFromJSON(json: any): GithubCallback200ResponseUser {
    return GithubCallback200ResponseUserFromJSONTyped(json, false);
}

export function GithubCallback200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubCallback200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'githubId': json['githubId'] == null ? undefined : json['githubId'],
    };
}

export function GithubCallback200ResponseUserToJSON(json: any): GithubCallback200ResponseUser {
    return GithubCallback200ResponseUserToJSONTyped(json, false);
}

export function GithubCallback200ResponseUserToJSONTyped(value?: GithubCallback200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'githubId': value['githubId'],
    };
}

