/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubCallback400Response
 */
export interface GithubCallback400Response {
    /**
     * 
     * @type {string}
     * @memberof GithubCallback400Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubCallback400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the GithubCallback400Response interface.
 */
export function instanceOfGithubCallback400Response(value: object): value is GithubCallback400Response {
    return true;
}

export function GithubCallback400ResponseFromJSON(json: any): GithubCallback400Response {
    return GithubCallback400ResponseFromJSONTyped(json, false);
}

export function GithubCallback400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubCallback400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GithubCallback400ResponseToJSON(json: any): GithubCallback400Response {
    return GithubCallback400ResponseToJSONTyped(json, false);
}

export function GithubCallback400ResponseToJSONTyped(value?: GithubCallback400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

