/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListStorageConfigs200Response
 */
export interface ListStorageConfigs200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListStorageConfigs200Response
     */
    storageKeys?: Array<string>;
}

/**
 * Check if a given object implements the ListStorageConfigs200Response interface.
 */
export function instanceOfListStorageConfigs200Response(value: object): value is ListStorageConfigs200Response {
    return true;
}

export function ListStorageConfigs200ResponseFromJSON(json: any): ListStorageConfigs200Response {
    return ListStorageConfigs200ResponseFromJSONTyped(json, false);
}

export function ListStorageConfigs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListStorageConfigs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'storageKeys': json['storageKeys'] == null ? undefined : json['storageKeys'],
    };
}

export function ListStorageConfigs200ResponseToJSON(json: any): ListStorageConfigs200Response {
    return ListStorageConfigs200ResponseToJSONTyped(json, false);
}

export function ListStorageConfigs200ResponseToJSONTyped(value?: ListStorageConfigs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageKeys': value['storageKeys'],
    };
}

