/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListGenerationRecords200ResponseDataItemsInner
 */
export interface ListGenerationRecords200ResponseDataItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    apiKeyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    templateId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    creditsUsed?: number;
    /**
     * 
     * @type {number}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    pdfSizeBytes?: number;
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    generationStart?: string;
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    generationEnd?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    sandbox?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListGenerationRecords200ResponseDataItemsInner
     */
    templateName?: string | null;
}

/**
 * Check if a given object implements the ListGenerationRecords200ResponseDataItemsInner interface.
 */
export function instanceOfListGenerationRecords200ResponseDataItemsInner(value: object): value is ListGenerationRecords200ResponseDataItemsInner {
    return true;
}

export function ListGenerationRecords200ResponseDataItemsInnerFromJSON(json: any): ListGenerationRecords200ResponseDataItemsInner {
    return ListGenerationRecords200ResponseDataItemsInnerFromJSONTyped(json, false);
}

export function ListGenerationRecords200ResponseDataItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListGenerationRecords200ResponseDataItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'apiKeyId': json['apiKeyId'] == null ? undefined : json['apiKeyId'],
        'templateId': json['templateId'] == null ? undefined : json['templateId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'status': json['status'] == null ? undefined : json['status'],
        'creditsUsed': json['creditsUsed'] == null ? undefined : json['creditsUsed'],
        'pdfSizeBytes': json['pdfSizeBytes'] == null ? undefined : json['pdfSizeBytes'],
        'generationStart': json['generationStart'] == null ? undefined : json['generationStart'],
        'generationEnd': json['generationEnd'] == null ? undefined : json['generationEnd'],
        'sandbox': json['sandbox'] == null ? undefined : json['sandbox'],
        'templateName': json['templateName'] == null ? undefined : json['templateName'],
    };
}

export function ListGenerationRecords200ResponseDataItemsInnerToJSON(json: any): ListGenerationRecords200ResponseDataItemsInner {
    return ListGenerationRecords200ResponseDataItemsInnerToJSONTyped(json, false);
}

export function ListGenerationRecords200ResponseDataItemsInnerToJSONTyped(value?: ListGenerationRecords200ResponseDataItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'apiKeyId': value['apiKeyId'],
        'templateId': value['templateId'],
        'userId': value['userId'],
        'status': value['status'],
        'creditsUsed': value['creditsUsed'],
        'pdfSizeBytes': value['pdfSizeBytes'],
        'generationStart': value['generationStart'],
        'generationEnd': value['generationEnd'],
        'sandbox': value['sandbox'],
        'templateName': value['templateName'],
    };
}

