/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTemplates200ResponseTemplatesInner } from './ListTemplates200ResponseTemplatesInner';
import {
    ListTemplates200ResponseTemplatesInnerFromJSON,
    ListTemplates200ResponseTemplatesInnerFromJSONTyped,
    ListTemplates200ResponseTemplatesInnerToJSON,
    ListTemplates200ResponseTemplatesInnerToJSONTyped,
} from './ListTemplates200ResponseTemplatesInner';

/**
 * 
 * @export
 * @interface ListTemplates200Response
 */
export interface ListTemplates200Response {
    /**
     * 
     * @type {Array<ListTemplates200ResponseTemplatesInner>}
     * @memberof ListTemplates200Response
     */
    templates?: Array<ListTemplates200ResponseTemplatesInner>;
}

/**
 * Check if a given object implements the ListTemplates200Response interface.
 */
export function instanceOfListTemplates200Response(value: object): value is ListTemplates200Response {
    return true;
}

export function ListTemplates200ResponseFromJSON(json: any): ListTemplates200Response {
    return ListTemplates200ResponseFromJSONTyped(json, false);
}

export function ListTemplates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTemplates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': json['templates'] == null ? undefined : ((json['templates'] as Array<any>).map(ListTemplates200ResponseTemplatesInnerFromJSON)),
    };
}

export function ListTemplates200ResponseToJSON(json: any): ListTemplates200Response {
    return ListTemplates200ResponseToJSONTyped(json, false);
}

export function ListTemplates200ResponseToJSONTyped(value?: ListTemplates200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': value['templates'] == null ? undefined : ((value['templates'] as Array<any>).map(ListTemplates200ResponseTemplatesInnerToJSON)),
    };
}

