/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListGenerationRecords200ResponseData } from './ListGenerationRecords200ResponseData';
import {
    ListGenerationRecords200ResponseDataFromJSON,
    ListGenerationRecords200ResponseDataFromJSONTyped,
    ListGenerationRecords200ResponseDataToJSON,
    ListGenerationRecords200ResponseDataToJSONTyped,
} from './ListGenerationRecords200ResponseData';

/**
 * 
 * @export
 * @interface ListGenerationRecords200Response
 */
export interface ListGenerationRecords200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListGenerationRecords200Response
     */
    success?: boolean;
    /**
     * 
     * @type {ListGenerationRecords200ResponseData}
     * @memberof ListGenerationRecords200Response
     */
    data?: ListGenerationRecords200ResponseData;
}

/**
 * Check if a given object implements the ListGenerationRecords200Response interface.
 */
export function instanceOfListGenerationRecords200Response(value: object): value is ListGenerationRecords200Response {
    return true;
}

export function ListGenerationRecords200ResponseFromJSON(json: any): ListGenerationRecords200Response {
    return ListGenerationRecords200ResponseFromJSONTyped(json, false);
}

export function ListGenerationRecords200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListGenerationRecords200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ListGenerationRecords200ResponseDataFromJSON(json['data']),
    };
}

export function ListGenerationRecords200ResponseToJSON(json: any): ListGenerationRecords200Response {
    return ListGenerationRecords200ResponseToJSONTyped(json, false);
}

export function ListGenerationRecords200ResponseToJSONTyped(value?: ListGenerationRecords200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ListGenerationRecords200ResponseDataToJSON(value['data']),
    };
}

