/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTemplates400Response
 */
export interface ListTemplates400Response {
    /**
     * Error unique identifier
     * @type {string}
     * @memberof ListTemplates400Response
     */
    error?: string;
    /**
     * Error message
     * @type {string}
     * @memberof ListTemplates400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ListTemplates400Response interface.
 */
export function instanceOfListTemplates400Response(value: object): value is ListTemplates400Response {
    return true;
}

export function ListTemplates400ResponseFromJSON(json: any): ListTemplates400Response {
    return ListTemplates400ResponseFromJSONTyped(json, false);
}

export function ListTemplates400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTemplates400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ListTemplates400ResponseToJSON(json: any): ListTemplates400Response {
    return ListTemplates400ResponseToJSONTyped(json, false);
}

export function ListTemplates400ResponseToJSONTyped(value?: ListTemplates400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

