/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTemplates200ResponseDataInner } from './ListTemplates200ResponseDataInner';
import {
    ListTemplates200ResponseDataInnerFromJSON,
    ListTemplates200ResponseDataInnerFromJSONTyped,
    ListTemplates200ResponseDataInnerToJSON,
    ListTemplates200ResponseDataInnerToJSONTyped,
} from './ListTemplates200ResponseDataInner';

/**
 * 
 * @export
 * @interface ListTemplates200Response
 */
export interface ListTemplates200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListTemplates200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<ListTemplates200ResponseDataInner>}
     * @memberof ListTemplates200Response
     */
    data?: Array<ListTemplates200ResponseDataInner>;
}

/**
 * Check if a given object implements the ListTemplates200Response interface.
 */
export function instanceOfListTemplates200Response(value: object): value is ListTemplates200Response {
    return true;
}

export function ListTemplates200ResponseFromJSON(json: any): ListTemplates200Response {
    return ListTemplates200ResponseFromJSONTyped(json, false);
}

export function ListTemplates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTemplates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListTemplates200ResponseDataInnerFromJSON)),
    };
}

export function ListTemplates200ResponseToJSON(json: any): ListTemplates200Response {
    return ListTemplates200ResponseToJSONTyped(json, false);
}

export function ListTemplates200ResponseToJSONTyped(value?: ListTemplates200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListTemplates200ResponseDataInnerToJSON)),
    };
}

