/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTemplates200ResponseDataInner
 */
export interface ListTemplates200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseDataInner
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseDataInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseDataInner
     */
    size?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseDataInner
     */
    orientation?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseDataInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseDataInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ListTemplates200ResponseDataInner interface.
 */
export function instanceOfListTemplates200ResponseDataInner(value: object): value is ListTemplates200ResponseDataInner {
    return true;
}

export function ListTemplates200ResponseDataInnerFromJSON(json: any): ListTemplates200ResponseDataInner {
    return ListTemplates200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListTemplates200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTemplates200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'content': json['content'] == null ? undefined : json['content'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'orientation': json['orientation'] == null ? undefined : json['orientation'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function ListTemplates200ResponseDataInnerToJSON(json: any): ListTemplates200ResponseDataInner {
    return ListTemplates200ResponseDataInnerToJSONTyped(json, false);
}

export function ListTemplates200ResponseDataInnerToJSONTyped(value?: ListTemplates200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'name': value['name'],
        'size': value['size'],
        'orientation': value['orientation'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

