/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthInvoicesGet200ResponsePagination } from './AuthInvoicesGet200ResponsePagination';
import {
    AuthInvoicesGet200ResponsePaginationFromJSON,
    AuthInvoicesGet200ResponsePaginationFromJSONTyped,
    AuthInvoicesGet200ResponsePaginationToJSON,
    AuthInvoicesGet200ResponsePaginationToJSONTyped,
} from './AuthInvoicesGet200ResponsePagination';
import type { ListGenerationRecords200ResponseDataItemsInner } from './ListGenerationRecords200ResponseDataItemsInner';
import {
    ListGenerationRecords200ResponseDataItemsInnerFromJSON,
    ListGenerationRecords200ResponseDataItemsInnerFromJSONTyped,
    ListGenerationRecords200ResponseDataItemsInnerToJSON,
    ListGenerationRecords200ResponseDataItemsInnerToJSONTyped,
} from './ListGenerationRecords200ResponseDataItemsInner';

/**
 * 
 * @export
 * @interface ListGenerationRecords200ResponseData
 */
export interface ListGenerationRecords200ResponseData {
    /**
     * 
     * @type {Array<ListGenerationRecords200ResponseDataItemsInner>}
     * @memberof ListGenerationRecords200ResponseData
     */
    items?: Array<ListGenerationRecords200ResponseDataItemsInner>;
    /**
     * 
     * @type {AuthInvoicesGet200ResponsePagination}
     * @memberof ListGenerationRecords200ResponseData
     */
    pagination?: AuthInvoicesGet200ResponsePagination;
}

/**
 * Check if a given object implements the ListGenerationRecords200ResponseData interface.
 */
export function instanceOfListGenerationRecords200ResponseData(value: object): value is ListGenerationRecords200ResponseData {
    return true;
}

export function ListGenerationRecords200ResponseDataFromJSON(json: any): ListGenerationRecords200ResponseData {
    return ListGenerationRecords200ResponseDataFromJSONTyped(json, false);
}

export function ListGenerationRecords200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListGenerationRecords200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ListGenerationRecords200ResponseDataItemsInnerFromJSON)),
        'pagination': json['pagination'] == null ? undefined : AuthInvoicesGet200ResponsePaginationFromJSON(json['pagination']),
    };
}

export function ListGenerationRecords200ResponseDataToJSON(json: any): ListGenerationRecords200ResponseData {
    return ListGenerationRecords200ResponseDataToJSONTyped(json, false);
}

export function ListGenerationRecords200ResponseDataToJSONTyped(value?: ListGenerationRecords200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ListGenerationRecords200ResponseDataItemsInnerToJSON)),
        'pagination': AuthInvoicesGet200ResponsePaginationToJSON(value['pagination']),
    };
}

