/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListApiKeys200ResponseApiKeysInner } from './ListApiKeys200ResponseApiKeysInner';
import {
    ListApiKeys200ResponseApiKeysInnerFromJSON,
    ListApiKeys200ResponseApiKeysInnerFromJSONTyped,
    ListApiKeys200ResponseApiKeysInnerToJSON,
    ListApiKeys200ResponseApiKeysInnerToJSONTyped,
} from './ListApiKeys200ResponseApiKeysInner';

/**
 * 
 * @export
 * @interface ListApiKeys200Response
 */
export interface ListApiKeys200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListApiKeys200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<ListApiKeys200ResponseApiKeysInner>}
     * @memberof ListApiKeys200Response
     */
    apiKeys?: Array<ListApiKeys200ResponseApiKeysInner>;
}

/**
 * Check if a given object implements the ListApiKeys200Response interface.
 */
export function instanceOfListApiKeys200Response(value: object): value is ListApiKeys200Response {
    return true;
}

export function ListApiKeys200ResponseFromJSON(json: any): ListApiKeys200Response {
    return ListApiKeys200ResponseFromJSONTyped(json, false);
}

export function ListApiKeys200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApiKeys200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'apiKeys': json['apiKeys'] == null ? undefined : ((json['apiKeys'] as Array<any>).map(ListApiKeys200ResponseApiKeysInnerFromJSON)),
    };
}

export function ListApiKeys200ResponseToJSON(json: any): ListApiKeys200Response {
    return ListApiKeys200ResponseToJSONTyped(json, false);
}

export function ListApiKeys200ResponseToJSONTyped(value?: ListApiKeys200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'apiKeys': value['apiKeys'] == null ? undefined : ((value['apiKeys'] as Array<any>).map(ListApiKeys200ResponseApiKeysInnerToJSON)),
    };
}

