/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListApiKeys200ResponseApiKeysInner
 */
export interface ListApiKeys200ResponseApiKeysInner {
    /**
     * 
     * @type {string}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    isActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    usageCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ListApiKeys200ResponseApiKeysInner
     */
    lastUsedAt?: string;
}

/**
 * Check if a given object implements the ListApiKeys200ResponseApiKeysInner interface.
 */
export function instanceOfListApiKeys200ResponseApiKeysInner(value: object): value is ListApiKeys200ResponseApiKeysInner {
    return true;
}

export function ListApiKeys200ResponseApiKeysInnerFromJSON(json: any): ListApiKeys200ResponseApiKeysInner {
    return ListApiKeys200ResponseApiKeysInnerFromJSONTyped(json, false);
}

export function ListApiKeys200ResponseApiKeysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListApiKeys200ResponseApiKeysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'key': json['key'] == null ? undefined : json['key'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'usageCount': json['usageCount'] == null ? undefined : json['usageCount'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'lastUsedAt': json['lastUsedAt'] == null ? undefined : json['lastUsedAt'],
    };
}

export function ListApiKeys200ResponseApiKeysInnerToJSON(json: any): ListApiKeys200ResponseApiKeysInner {
    return ListApiKeys200ResponseApiKeysInnerToJSONTyped(json, false);
}

export function ListApiKeys200ResponseApiKeysInnerToJSONTyped(value?: ListApiKeys200ResponseApiKeysInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'key': value['key'],
        'description': value['description'],
        'isActive': value['isActive'],
        'usageCount': value['usageCount'],
        'createdAt': value['createdAt'],
        'lastUsedAt': value['lastUsedAt'],
    };
}

