/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTemplates200ResponseTemplatesInner
 */
export interface ListTemplates200ResponseTemplatesInner {
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseTemplatesInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseTemplatesInner
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseTemplatesInner
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseTemplatesInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseTemplatesInner
     */
    size?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseTemplatesInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ListTemplates200ResponseTemplatesInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ListTemplates200ResponseTemplatesInner interface.
 */
export function instanceOfListTemplates200ResponseTemplatesInner(value: object): value is ListTemplates200ResponseTemplatesInner {
    return true;
}

export function ListTemplates200ResponseTemplatesInnerFromJSON(json: any): ListTemplates200ResponseTemplatesInner {
    return ListTemplates200ResponseTemplatesInnerFromJSONTyped(json, false);
}

export function ListTemplates200ResponseTemplatesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTemplates200ResponseTemplatesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'content': json['content'] == null ? undefined : json['content'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function ListTemplates200ResponseTemplatesInnerToJSON(json: any): ListTemplates200ResponseTemplatesInner {
    return ListTemplates200ResponseTemplatesInnerToJSONTyped(json, false);
}

export function ListTemplates200ResponseTemplatesInnerToJSONTyped(value?: ListTemplates200ResponseTemplatesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'content': value['content'],
        'name': value['name'],
        'size': value['size'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

