/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpResourcesReadPostRequest
 */
export interface McpResourcesReadPostRequest {
    /**
     * The resource URI (e.g., template://abc123)
     * @type {string}
     * @memberof McpResourcesReadPostRequest
     */
    uri: string;
}

/**
 * Check if a given object implements the McpResourcesReadPostRequest interface.
 */
export function instanceOfMcpResourcesReadPostRequest(value: object): value is McpResourcesReadPostRequest {
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function McpResourcesReadPostRequestFromJSON(json: any): McpResourcesReadPostRequest {
    return McpResourcesReadPostRequestFromJSONTyped(json, false);
}

export function McpResourcesReadPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpResourcesReadPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uri': json['uri'],
    };
}

export function McpResourcesReadPostRequestToJSON(json: any): McpResourcesReadPostRequest {
    return McpResourcesReadPostRequestToJSONTyped(json, false);
}

export function McpResourcesReadPostRequestToJSONTyped(value?: McpResourcesReadPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uri': value['uri'],
    };
}

