/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpServerInfoGet200ResponseCapabilities
 */
export interface McpServerInfoGet200ResponseCapabilities {
    /**
     * 
     * @type {boolean}
     * @memberof McpServerInfoGet200ResponseCapabilities
     */
    tools?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof McpServerInfoGet200ResponseCapabilities
     */
    resources?: boolean;
}

/**
 * Check if a given object implements the McpServerInfoGet200ResponseCapabilities interface.
 */
export function instanceOfMcpServerInfoGet200ResponseCapabilities(value: object): value is McpServerInfoGet200ResponseCapabilities {
    return true;
}

export function McpServerInfoGet200ResponseCapabilitiesFromJSON(json: any): McpServerInfoGet200ResponseCapabilities {
    return McpServerInfoGet200ResponseCapabilitiesFromJSONTyped(json, false);
}

export function McpServerInfoGet200ResponseCapabilitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpServerInfoGet200ResponseCapabilities {
    if (json == null) {
        return json;
    }
    return {
        
        'tools': json['tools'] == null ? undefined : json['tools'],
        'resources': json['resources'] == null ? undefined : json['resources'],
    };
}

export function McpServerInfoGet200ResponseCapabilitiesToJSON(json: any): McpServerInfoGet200ResponseCapabilities {
    return McpServerInfoGet200ResponseCapabilitiesToJSONTyped(json, false);
}

export function McpServerInfoGet200ResponseCapabilitiesToJSONTyped(value?: McpServerInfoGet200ResponseCapabilities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tools': value['tools'],
        'resources': value['resources'],
    };
}

