/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { McpServerInfoGet200ResponseCapabilities } from './McpServerInfoGet200ResponseCapabilities';
import {
    McpServerInfoGet200ResponseCapabilitiesFromJSON,
    McpServerInfoGet200ResponseCapabilitiesFromJSONTyped,
    McpServerInfoGet200ResponseCapabilitiesToJSON,
    McpServerInfoGet200ResponseCapabilitiesToJSONTyped,
} from './McpServerInfoGet200ResponseCapabilities';

/**
 * 
 * @export
 * @interface McpServerInfoGet200Response
 */
export interface McpServerInfoGet200Response {
    /**
     * 
     * @type {string}
     * @memberof McpServerInfoGet200Response
     */
    protocolVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof McpServerInfoGet200Response
     */
    serverName?: string;
    /**
     * 
     * @type {string}
     * @memberof McpServerInfoGet200Response
     */
    serverVersion?: string;
    /**
     * 
     * @type {McpServerInfoGet200ResponseCapabilities}
     * @memberof McpServerInfoGet200Response
     */
    capabilities?: McpServerInfoGet200ResponseCapabilities;
}

/**
 * Check if a given object implements the McpServerInfoGet200Response interface.
 */
export function instanceOfMcpServerInfoGet200Response(value: object): value is McpServerInfoGet200Response {
    return true;
}

export function McpServerInfoGet200ResponseFromJSON(json: any): McpServerInfoGet200Response {
    return McpServerInfoGet200ResponseFromJSONTyped(json, false);
}

export function McpServerInfoGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpServerInfoGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'protocolVersion': json['protocol_version'] == null ? undefined : json['protocol_version'],
        'serverName': json['server_name'] == null ? undefined : json['server_name'],
        'serverVersion': json['server_version'] == null ? undefined : json['server_version'],
        'capabilities': json['capabilities'] == null ? undefined : McpServerInfoGet200ResponseCapabilitiesFromJSON(json['capabilities']),
    };
}

export function McpServerInfoGet200ResponseToJSON(json: any): McpServerInfoGet200Response {
    return McpServerInfoGet200ResponseToJSONTyped(json, false);
}

export function McpServerInfoGet200ResponseToJSONTyped(value?: McpServerInfoGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protocol_version': value['protocolVersion'],
        'server_name': value['serverName'],
        'server_version': value['serverVersion'],
        'capabilities': McpServerInfoGet200ResponseCapabilitiesToJSON(value['capabilities']),
    };
}

