/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpToolsCallPostRequest
 */
export interface McpToolsCallPostRequest {
    /**
     * The name of the tool to call
     * @type {string}
     * @memberof McpToolsCallPostRequest
     */
    name: McpToolsCallPostRequestNameEnum;
    /**
     * Tool-specific arguments
     * @type {object}
     * @memberof McpToolsCallPostRequest
     */
    arguments: object;
}


/**
 * @export
 */
export const McpToolsCallPostRequestNameEnum = {
    GeneratePdf: 'generate_pdf',
    ListTemplates: 'list_templates',
    GetTemplateDetails: 'get_template_details',
    GetUserCredits: 'get_user_credits'
} as const;
export type McpToolsCallPostRequestNameEnum = typeof McpToolsCallPostRequestNameEnum[keyof typeof McpToolsCallPostRequestNameEnum];


/**
 * Check if a given object implements the McpToolsCallPostRequest interface.
 */
export function instanceOfMcpToolsCallPostRequest(value: object): value is McpToolsCallPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('arguments' in value) || value['arguments'] === undefined) return false;
    return true;
}

export function McpToolsCallPostRequestFromJSON(json: any): McpToolsCallPostRequest {
    return McpToolsCallPostRequestFromJSONTyped(json, false);
}

export function McpToolsCallPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpToolsCallPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'arguments': json['arguments'],
    };
}

export function McpToolsCallPostRequestToJSON(json: any): McpToolsCallPostRequest {
    return McpToolsCallPostRequestToJSONTyped(json, false);
}

export function McpToolsCallPostRequestToJSONTyped(value?: McpToolsCallPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'arguments': value['arguments'],
    };
}

