/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpWellKnownMcpJsonGet200ResponseEndpointsTools
 */
export interface McpWellKnownMcpJsonGet200ResponseEndpointsTools {
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseEndpointsTools
     */
    list?: string;
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseEndpointsTools
     */
    call?: string;
}

/**
 * Check if a given object implements the McpWellKnownMcpJsonGet200ResponseEndpointsTools interface.
 */
export function instanceOfMcpWellKnownMcpJsonGet200ResponseEndpointsTools(value: object): value is McpWellKnownMcpJsonGet200ResponseEndpointsTools {
    return true;
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsToolsFromJSON(json: any): McpWellKnownMcpJsonGet200ResponseEndpointsTools {
    return McpWellKnownMcpJsonGet200ResponseEndpointsToolsFromJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsToolsFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpWellKnownMcpJsonGet200ResponseEndpointsTools {
    if (json == null) {
        return json;
    }
    return {
        
        'list': json['list'] == null ? undefined : json['list'],
        'call': json['call'] == null ? undefined : json['call'],
    };
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsToolsToJSON(json: any): McpWellKnownMcpJsonGet200ResponseEndpointsTools {
    return McpWellKnownMcpJsonGet200ResponseEndpointsToolsToJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsToolsToJSONTyped(value?: McpWellKnownMcpJsonGet200ResponseEndpointsTools | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': value['list'],
        'call': value['call'],
    };
}

