/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpWellKnownMcpJsonGet200ResponseServerInfo
 */
export interface McpWellKnownMcpJsonGet200ResponseServerInfo {
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseServerInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseServerInfo
     */
    version?: string;
}

/**
 * Check if a given object implements the McpWellKnownMcpJsonGet200ResponseServerInfo interface.
 */
export function instanceOfMcpWellKnownMcpJsonGet200ResponseServerInfo(value: object): value is McpWellKnownMcpJsonGet200ResponseServerInfo {
    return true;
}

export function McpWellKnownMcpJsonGet200ResponseServerInfoFromJSON(json: any): McpWellKnownMcpJsonGet200ResponseServerInfo {
    return McpWellKnownMcpJsonGet200ResponseServerInfoFromJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpWellKnownMcpJsonGet200ResponseServerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function McpWellKnownMcpJsonGet200ResponseServerInfoToJSON(json: any): McpWellKnownMcpJsonGet200ResponseServerInfo {
    return McpWellKnownMcpJsonGet200ResponseServerInfoToJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseServerInfoToJSONTyped(value?: McpWellKnownMcpJsonGet200ResponseServerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
    };
}

