/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpWellKnownMcpJsonGet200ResponseAuthentication
 */
export interface McpWellKnownMcpJsonGet200ResponseAuthentication {
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseAuthentication
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseAuthentication
     */
    _in?: string;
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseAuthentication
     */
    name?: string;
}

/**
 * Check if a given object implements the McpWellKnownMcpJsonGet200ResponseAuthentication interface.
 */
export function instanceOfMcpWellKnownMcpJsonGet200ResponseAuthentication(value: object): value is McpWellKnownMcpJsonGet200ResponseAuthentication {
    return true;
}

export function McpWellKnownMcpJsonGet200ResponseAuthenticationFromJSON(json: any): McpWellKnownMcpJsonGet200ResponseAuthentication {
    return McpWellKnownMcpJsonGet200ResponseAuthenticationFromJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseAuthenticationFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpWellKnownMcpJsonGet200ResponseAuthentication {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        '_in': json['in'] == null ? undefined : json['in'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function McpWellKnownMcpJsonGet200ResponseAuthenticationToJSON(json: any): McpWellKnownMcpJsonGet200ResponseAuthentication {
    return McpWellKnownMcpJsonGet200ResponseAuthenticationToJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseAuthenticationToJSONTyped(value?: McpWellKnownMcpJsonGet200ResponseAuthentication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'in': value['_in'],
        'name': value['name'],
    };
}

