/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { McpWellKnownMcpJsonGet200ResponseCapabilities } from './McpWellKnownMcpJsonGet200ResponseCapabilities';
import {
    McpWellKnownMcpJsonGet200ResponseCapabilitiesFromJSON,
    McpWellKnownMcpJsonGet200ResponseCapabilitiesFromJSONTyped,
    McpWellKnownMcpJsonGet200ResponseCapabilitiesToJSON,
    McpWellKnownMcpJsonGet200ResponseCapabilitiesToJSONTyped,
} from './McpWellKnownMcpJsonGet200ResponseCapabilities';
import type { McpWellKnownMcpJsonGet200ResponseEndpoints } from './McpWellKnownMcpJsonGet200ResponseEndpoints';
import {
    McpWellKnownMcpJsonGet200ResponseEndpointsFromJSON,
    McpWellKnownMcpJsonGet200ResponseEndpointsFromJSONTyped,
    McpWellKnownMcpJsonGet200ResponseEndpointsToJSON,
    McpWellKnownMcpJsonGet200ResponseEndpointsToJSONTyped,
} from './McpWellKnownMcpJsonGet200ResponseEndpoints';
import type { McpWellKnownMcpJsonGet200ResponseAuthentication } from './McpWellKnownMcpJsonGet200ResponseAuthentication';
import {
    McpWellKnownMcpJsonGet200ResponseAuthenticationFromJSON,
    McpWellKnownMcpJsonGet200ResponseAuthenticationFromJSONTyped,
    McpWellKnownMcpJsonGet200ResponseAuthenticationToJSON,
    McpWellKnownMcpJsonGet200ResponseAuthenticationToJSONTyped,
} from './McpWellKnownMcpJsonGet200ResponseAuthentication';
import type { McpWellKnownMcpJsonGet200ResponseServerInfo } from './McpWellKnownMcpJsonGet200ResponseServerInfo';
import {
    McpWellKnownMcpJsonGet200ResponseServerInfoFromJSON,
    McpWellKnownMcpJsonGet200ResponseServerInfoFromJSONTyped,
    McpWellKnownMcpJsonGet200ResponseServerInfoToJSON,
    McpWellKnownMcpJsonGet200ResponseServerInfoToJSONTyped,
} from './McpWellKnownMcpJsonGet200ResponseServerInfo';

/**
 * 
 * @export
 * @interface McpWellKnownMcpJsonGet200Response
 */
export interface McpWellKnownMcpJsonGet200Response {
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200Response
     */
    mcpVersion?: string;
    /**
     * 
     * @type {McpWellKnownMcpJsonGet200ResponseServerInfo}
     * @memberof McpWellKnownMcpJsonGet200Response
     */
    serverInfo?: McpWellKnownMcpJsonGet200ResponseServerInfo;
    /**
     * 
     * @type {McpWellKnownMcpJsonGet200ResponseCapabilities}
     * @memberof McpWellKnownMcpJsonGet200Response
     */
    capabilities?: McpWellKnownMcpJsonGet200ResponseCapabilities;
    /**
     * 
     * @type {McpWellKnownMcpJsonGet200ResponseEndpoints}
     * @memberof McpWellKnownMcpJsonGet200Response
     */
    endpoints?: McpWellKnownMcpJsonGet200ResponseEndpoints;
    /**
     * 
     * @type {McpWellKnownMcpJsonGet200ResponseAuthentication}
     * @memberof McpWellKnownMcpJsonGet200Response
     */
    authentication?: McpWellKnownMcpJsonGet200ResponseAuthentication;
}

/**
 * Check if a given object implements the McpWellKnownMcpJsonGet200Response interface.
 */
export function instanceOfMcpWellKnownMcpJsonGet200Response(value: object): value is McpWellKnownMcpJsonGet200Response {
    return true;
}

export function McpWellKnownMcpJsonGet200ResponseFromJSON(json: any): McpWellKnownMcpJsonGet200Response {
    return McpWellKnownMcpJsonGet200ResponseFromJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpWellKnownMcpJsonGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mcpVersion': json['mcpVersion'] == null ? undefined : json['mcpVersion'],
        'serverInfo': json['serverInfo'] == null ? undefined : McpWellKnownMcpJsonGet200ResponseServerInfoFromJSON(json['serverInfo']),
        'capabilities': json['capabilities'] == null ? undefined : McpWellKnownMcpJsonGet200ResponseCapabilitiesFromJSON(json['capabilities']),
        'endpoints': json['endpoints'] == null ? undefined : McpWellKnownMcpJsonGet200ResponseEndpointsFromJSON(json['endpoints']),
        'authentication': json['authentication'] == null ? undefined : McpWellKnownMcpJsonGet200ResponseAuthenticationFromJSON(json['authentication']),
    };
}

export function McpWellKnownMcpJsonGet200ResponseToJSON(json: any): McpWellKnownMcpJsonGet200Response {
    return McpWellKnownMcpJsonGet200ResponseToJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseToJSONTyped(value?: McpWellKnownMcpJsonGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mcpVersion': value['mcpVersion'],
        'serverInfo': McpWellKnownMcpJsonGet200ResponseServerInfoToJSON(value['serverInfo']),
        'capabilities': McpWellKnownMcpJsonGet200ResponseCapabilitiesToJSON(value['capabilities']),
        'endpoints': McpWellKnownMcpJsonGet200ResponseEndpointsToJSON(value['endpoints']),
        'authentication': McpWellKnownMcpJsonGet200ResponseAuthenticationToJSON(value['authentication']),
    };
}

