/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpWellKnownMcpJsonGet200ResponseEndpointsResources
 */
export interface McpWellKnownMcpJsonGet200ResponseEndpointsResources {
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseEndpointsResources
     */
    list?: string;
    /**
     * 
     * @type {string}
     * @memberof McpWellKnownMcpJsonGet200ResponseEndpointsResources
     */
    read?: string;
}

/**
 * Check if a given object implements the McpWellKnownMcpJsonGet200ResponseEndpointsResources interface.
 */
export function instanceOfMcpWellKnownMcpJsonGet200ResponseEndpointsResources(value: object): value is McpWellKnownMcpJsonGet200ResponseEndpointsResources {
    return true;
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsResourcesFromJSON(json: any): McpWellKnownMcpJsonGet200ResponseEndpointsResources {
    return McpWellKnownMcpJsonGet200ResponseEndpointsResourcesFromJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpWellKnownMcpJsonGet200ResponseEndpointsResources {
    if (json == null) {
        return json;
    }
    return {
        
        'list': json['list'] == null ? undefined : json['list'],
        'read': json['read'] == null ? undefined : json['read'],
    };
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsResourcesToJSON(json: any): McpWellKnownMcpJsonGet200ResponseEndpointsResources {
    return McpWellKnownMcpJsonGet200ResponseEndpointsResourcesToJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsResourcesToJSONTyped(value?: McpWellKnownMcpJsonGet200ResponseEndpointsResources | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': value['list'],
        'read': value['read'],
    };
}

