/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { McpWellKnownMcpJsonGet200ResponseEndpointsResources } from './McpWellKnownMcpJsonGet200ResponseEndpointsResources';
import {
    McpWellKnownMcpJsonGet200ResponseEndpointsResourcesFromJSON,
    McpWellKnownMcpJsonGet200ResponseEndpointsResourcesFromJSONTyped,
    McpWellKnownMcpJsonGet200ResponseEndpointsResourcesToJSON,
    McpWellKnownMcpJsonGet200ResponseEndpointsResourcesToJSONTyped,
} from './McpWellKnownMcpJsonGet200ResponseEndpointsResources';
import type { McpWellKnownMcpJsonGet200ResponseEndpointsTools } from './McpWellKnownMcpJsonGet200ResponseEndpointsTools';
import {
    McpWellKnownMcpJsonGet200ResponseEndpointsToolsFromJSON,
    McpWellKnownMcpJsonGet200ResponseEndpointsToolsFromJSONTyped,
    McpWellKnownMcpJsonGet200ResponseEndpointsToolsToJSON,
    McpWellKnownMcpJsonGet200ResponseEndpointsToolsToJSONTyped,
} from './McpWellKnownMcpJsonGet200ResponseEndpointsTools';

/**
 * 
 * @export
 * @interface McpWellKnownMcpJsonGet200ResponseEndpoints
 */
export interface McpWellKnownMcpJsonGet200ResponseEndpoints {
    /**
     * 
     * @type {McpWellKnownMcpJsonGet200ResponseEndpointsTools}
     * @memberof McpWellKnownMcpJsonGet200ResponseEndpoints
     */
    tools?: McpWellKnownMcpJsonGet200ResponseEndpointsTools;
    /**
     * 
     * @type {McpWellKnownMcpJsonGet200ResponseEndpointsResources}
     * @memberof McpWellKnownMcpJsonGet200ResponseEndpoints
     */
    resources?: McpWellKnownMcpJsonGet200ResponseEndpointsResources;
}

/**
 * Check if a given object implements the McpWellKnownMcpJsonGet200ResponseEndpoints interface.
 */
export function instanceOfMcpWellKnownMcpJsonGet200ResponseEndpoints(value: object): value is McpWellKnownMcpJsonGet200ResponseEndpoints {
    return true;
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsFromJSON(json: any): McpWellKnownMcpJsonGet200ResponseEndpoints {
    return McpWellKnownMcpJsonGet200ResponseEndpointsFromJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpWellKnownMcpJsonGet200ResponseEndpoints {
    if (json == null) {
        return json;
    }
    return {
        
        'tools': json['tools'] == null ? undefined : McpWellKnownMcpJsonGet200ResponseEndpointsToolsFromJSON(json['tools']),
        'resources': json['resources'] == null ? undefined : McpWellKnownMcpJsonGet200ResponseEndpointsResourcesFromJSON(json['resources']),
    };
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsToJSON(json: any): McpWellKnownMcpJsonGet200ResponseEndpoints {
    return McpWellKnownMcpJsonGet200ResponseEndpointsToJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseEndpointsToJSONTyped(value?: McpWellKnownMcpJsonGet200ResponseEndpoints | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tools': McpWellKnownMcpJsonGet200ResponseEndpointsToolsToJSON(value['tools']),
        'resources': McpWellKnownMcpJsonGet200ResponseEndpointsResourcesToJSON(value['resources']),
    };
}

