/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface McpWellKnownMcpJsonGet200ResponseCapabilities
 */
export interface McpWellKnownMcpJsonGet200ResponseCapabilities {
    /**
     * 
     * @type {boolean}
     * @memberof McpWellKnownMcpJsonGet200ResponseCapabilities
     */
    tools?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof McpWellKnownMcpJsonGet200ResponseCapabilities
     */
    resources?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof McpWellKnownMcpJsonGet200ResponseCapabilities
     */
    prompts?: boolean;
}

/**
 * Check if a given object implements the McpWellKnownMcpJsonGet200ResponseCapabilities interface.
 */
export function instanceOfMcpWellKnownMcpJsonGet200ResponseCapabilities(value: object): value is McpWellKnownMcpJsonGet200ResponseCapabilities {
    return true;
}

export function McpWellKnownMcpJsonGet200ResponseCapabilitiesFromJSON(json: any): McpWellKnownMcpJsonGet200ResponseCapabilities {
    return McpWellKnownMcpJsonGet200ResponseCapabilitiesFromJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseCapabilitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): McpWellKnownMcpJsonGet200ResponseCapabilities {
    if (json == null) {
        return json;
    }
    return {
        
        'tools': json['tools'] == null ? undefined : json['tools'],
        'resources': json['resources'] == null ? undefined : json['resources'],
        'prompts': json['prompts'] == null ? undefined : json['prompts'],
    };
}

export function McpWellKnownMcpJsonGet200ResponseCapabilitiesToJSON(json: any): McpWellKnownMcpJsonGet200ResponseCapabilities {
    return McpWellKnownMcpJsonGet200ResponseCapabilitiesToJSONTyped(json, false);
}

export function McpWellKnownMcpJsonGet200ResponseCapabilitiesToJSONTyped(value?: McpWellKnownMcpJsonGet200ResponseCapabilities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tools': value['tools'],
        'resources': value['resources'],
        'prompts': value['prompts'],
    };
}

