/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTemplateRequest
 */
export interface UpdateTemplateRequest {
    /**
     * HTML template content
     * @type {string}
     * @memberof UpdateTemplateRequest
     */
    content?: string;
    /**
     * Name of the template
     * @type {string}
     * @memberof UpdateTemplateRequest
     */
    name?: string;
    /**
     * Page size (e.g., A4, Letter, 100mm|100mm, 10in|10in)
     * @type {string}
     * @memberof UpdateTemplateRequest
     */
    size?: string;
    /**
     * Page orientation (portrait or landscape). Defaults to portrait
     * @type {string}
     * @memberof UpdateTemplateRequest
     */
    orientation?: string;
}

/**
 * Check if a given object implements the UpdateTemplateRequest interface.
 */
export function instanceOfUpdateTemplateRequest(value: object): value is UpdateTemplateRequest {
    return true;
}

export function UpdateTemplateRequestFromJSON(json: any): UpdateTemplateRequest {
    return UpdateTemplateRequestFromJSONTyped(json, false);
}

export function UpdateTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'orientation': json['orientation'] == null ? undefined : json['orientation'],
    };
}

export function UpdateTemplateRequestToJSON(json: any): UpdateTemplateRequest {
    return UpdateTemplateRequestToJSONTyped(json, false);
}

export function UpdateTemplateRequestToJSONTyped(value?: UpdateTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'name': value['name'],
        'size': value['size'],
        'orientation': value['orientation'],
    };
}

