/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateStorageConfigRequest
 */
export interface UpdateStorageConfigRequest {
    /**
     * Type of storage
     * @type {string}
     * @memberof UpdateStorageConfigRequest
     */
    storageType: UpdateStorageConfigRequestStorageTypeEnum;
}


/**
 * @export
 */
export const UpdateStorageConfigRequestStorageTypeEnum = {
    S3: 's3',
    AzureBlob: 'azureBlob',
    Ftp: 'ftp'
} as const;
export type UpdateStorageConfigRequestStorageTypeEnum = typeof UpdateStorageConfigRequestStorageTypeEnum[keyof typeof UpdateStorageConfigRequestStorageTypeEnum];


/**
 * Check if a given object implements the UpdateStorageConfigRequest interface.
 */
export function instanceOfUpdateStorageConfigRequest(value: object): value is UpdateStorageConfigRequest {
    if (!('storageType' in value) || value['storageType'] === undefined) return false;
    return true;
}

export function UpdateStorageConfigRequestFromJSON(json: any): UpdateStorageConfigRequest {
    return UpdateStorageConfigRequestFromJSONTyped(json, false);
}

export function UpdateStorageConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStorageConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storageType': json['storageType'],
    };
}

export function UpdateStorageConfigRequestToJSON(json: any): UpdateStorageConfigRequest {
    return UpdateStorageConfigRequestToJSONTyped(json, false);
}

export function UpdateStorageConfigRequestToJSONTyped(value?: UpdateStorageConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageType': value['storageType'],
    };
}

