/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhooksPolarPostRequest
 */
export interface WebhooksPolarPostRequest {
    /**
     * 
     * @type {string}
     * @memberof WebhooksPolarPostRequest
     */
    type?: string;
    /**
     * 
     * @type {object}
     * @memberof WebhooksPolarPostRequest
     */
    data?: object;
}

/**
 * Check if a given object implements the WebhooksPolarPostRequest interface.
 */
export function instanceOfWebhooksPolarPostRequest(value: object): value is WebhooksPolarPostRequest {
    return true;
}

export function WebhooksPolarPostRequestFromJSON(json: any): WebhooksPolarPostRequest {
    return WebhooksPolarPostRequestFromJSONTyped(json, false);
}

export function WebhooksPolarPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksPolarPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function WebhooksPolarPostRequestToJSON(json: any): WebhooksPolarPostRequest {
    return WebhooksPolarPostRequestToJSONTyped(json, false);
}

export function WebhooksPolarPostRequestToJSONTyped(value?: WebhooksPolarPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'data': value['data'],
    };
}

